export interface DeveloperRoadmapItem {
  id: string;
  name: string;
  category: string;
  description: string;
  moduleCount: number;
  featured?: boolean;
}

export const DEVELOPER_ROADMAPS: DeveloperRoadmapItem[] = [
  { id: "ai-agents", name: "AI Agents", category: "AI & Data Science", description: "Learn how to build autonomous AI agents, tool invocation, memory & MCP.", moduleCount: 101, featured: true },
  { id: "ai-engineer", name: "AI Engineer", category: "AI & Data Science", description: "Master LLMs, fine-tuning, RAG, prompt engineering & vector databases.", moduleCount: 84, featured: true },
  { id: "ai-data-scientist", name: "AI Data Scientist", category: "AI & Data Science", description: "Data manipulation, machine learning models, statistical analysis & AI integration.", moduleCount: 78 },
  { id: "ai-product-builder", name: "AI Product Builder", category: "AI & Data Science", description: "Designing, prototyping, and shipping user-centric AI-powered applications.", moduleCount: 65 },
  { id: "ai-red-teaming", name: "AI Red Teaming", category: "Security", description: "Vulnerability analysis, prompt injection defense, and LLM security audits.", moduleCount: 52 },
  { id: "android", name: "Android Developer", category: "Mobile & Apps", description: "Kotlin, Jetpack Compose, Android SDK, and modern mobile app architecture.", moduleCount: 88 },
  { id: "angular", name: "Angular Developer", category: "Frontend & Web", description: "RxJS, NgRx, TypeScript, components, directives, and enterprise web architecture.", moduleCount: 70 },
  { id: "api-design", name: "API Design", category: "Architecture & CS", description: "REST, GraphQL, gRPC, OpenAPI specs, rate limiting, and security design.", moduleCount: 64 },
  { id: "aspnet-core", name: "ASP.NET Core", category: "Backend & Systems", description: "C#, Entity Framework Core, Web APIs, authentication, and cloud deployment.", moduleCount: 72 },
  { id: "aws", name: "AWS Cloud Architect", category: "DevOps & Cloud", description: "EC2, S3, Lambda, CloudFront, IAM, DynamoDB, and cloud infrastructure.", moduleCount: 95, featured: true },
  { id: "backend", name: "Backend Developer", category: "Backend & Systems", description: "Databases, caching, APIs, authentication, server architecture, and security.", moduleCount: 110, featured: true },
  { id: "backend-beginner", name: "Backend (Beginner)", category: "Backend & Systems", description: "Introduction to server programming, HTTP basics, node.js, and relational DBs.", moduleCount: 45 },
  { id: "bi-analyst", name: "BI Analyst", category: "AI & Data Science", description: "SQL querying, data visualization, PowerBI, Tableau, and business metrics.", moduleCount: 58 },
  { id: "blockchain", name: "Blockchain Developer", category: "Specialized Skill", description: "Solidity, Ethereum, Web3.js, smart contracts, consensus protocols, and DeFi.", moduleCount: 76 },
  { id: "c", name: "C Programming", category: "Backend & Systems", description: "Memory management, pointers, system calls, data structures, and compilers.", moduleCount: 60 },
  { id: "claude-code", name: "Claude Code & MCP", category: "AI & Data Science", description: "Building tools, subagents, and Model Context Protocol servers for AI assistants.", moduleCount: 48, featured: true },
  { id: "cloudflare", name: "Cloudflare Developer", category: "DevOps & Cloud", description: "Workers, Pages, R2 storage, D1 database, edge computing, and DNS routing.", moduleCount: 54 },
  { id: "code-review", name: "Code Reviewer", category: "Security", description: "Best practices, static analysis, security vulnerabilities, and PR feedback.", moduleCount: 42 },
  { id: "computer-science", name: "Computer Science", category: "Architecture & CS", description: "Algorithms, data structures, OS, networking, theory of computation, and databases.", moduleCount: 120, featured: true },
  { id: "cpp", name: "C++ Developer", category: "Backend & Systems", description: "Modern C++17/20, STL, templates, memory management, and high-performance apps.", moduleCount: 82 },
  { id: "css", name: "CSS Architecture", category: "Frontend & Web", description: "Flexbox, Grid, animations, Tailwind CSS, custom properties, and design systems.", moduleCount: 65 },
  { id: "cyber-security", name: "Cyber Security", category: "Security", description: "Ethical hacking, network security, cryptography, penetration testing, and SIEM.", moduleCount: 105, featured: true },
  { id: "data-analyst", name: "Data Analyst", category: "AI & Data Science", description: "Python, Pandas, NumPy, SQL, data cleaning, visualization, and hypothesis testing.", moduleCount: 80, featured: true },
  { id: "data-engineer", name: "Data Engineer", category: "AI & Data Science", description: "ETL pipelines, Spark, Airflow, Snowflake, Kafka, and big data architecture.", moduleCount: 92 },
  { id: "datastructures-and-algorithms", name: "Data Structures & Algorithms", category: "Architecture & CS", description: "Arrays, trees, graphs, sorting, dynamic programming, and Big-O analysis.", moduleCount: 98, featured: true },
  { id: "design-system", name: "Design System Specialist", category: "Frontend & Web", description: "Figma tokens, atomic components, accessibility, and component libraries.", moduleCount: 56 },
  { id: "devops", name: "DevOps Engineer", category: "DevOps & Cloud", description: "CI/CD pipelines, Docker, Kubernetes, Terraform, Prometheus, and Ansible.", moduleCount: 115, featured: true },
  { id: "devops-beginner", name: "DevOps (Beginner)", category: "DevOps & Cloud", description: "Linux fundamentals, Git, basic scripting, Docker containers, and CI/CD concepts.", moduleCount: 48 },
  { id: "devrel", name: "DevRel Engineer", category: "Specialized Skill", description: "Technical documentation, community building, developer advocacy, and demos.", moduleCount: 40 },
  { id: "devsecops", name: "DevSecOps", category: "Security", description: "Security in CI/CD, SAST/DAST tools, container scanning, and compliance.", moduleCount: 68 },
  { id: "django", name: "Django Developer", category: "Backend & Systems", description: "Python web framework, ORM, REST framework, authentication, and deployment.", moduleCount: 62 },
  { id: "docker", name: "Docker Specialist", category: "DevOps & Cloud", description: "Containers, Dockerfiles, multi-stage builds, Docker Compose, and networking.", moduleCount: 58 },
  { id: "elasticsearch", name: "Elasticsearch Specialist", category: "Backend & Systems", description: "Full-text search, indexing, mapping, aggregation, and Kibana dashboards.", moduleCount: 46 },
  { id: "engineering-manager", name: "Engineering Manager", category: "Specialized Skill", description: "Team leadership, 1-on-1s, hiring, tech strategy, agile delivery, and mentorship.", moduleCount: 75 },
  { id: "flutter", name: "Flutter Developer", category: "Mobile & Apps", description: "Dart, Flutter widgets, state management (Bloc/Riverpod), and cross-platform apps.", moduleCount: 84 },
  { id: "frontend", name: "Frontend Developer", category: "Frontend & Web", description: "HTML, CSS, JavaScript, React, Web APIs, performance, and responsive design.", moduleCount: 125, featured: true },
  { id: "frontend-beginner", name: "Frontend (Beginner)", category: "Frontend & Web", description: "HTML basics, CSS styling, fundamental JavaScript, and building web pages.", moduleCount: 40 },
  { id: "full-stack", name: "Full-Stack Developer", category: "Backend & Systems", description: "Frontend + Backend end-to-end web applications, APIs, and cloud deployments.", moduleCount: 135, featured: true },
  { id: "game-developer", name: "Game Developer", category: "Specialized Skill", description: "Unity, Unreal Engine, C#, C++, shaders, physics engines, and 3D graphics.", moduleCount: 90 },
  { id: "git-github", name: "Git & GitHub", category: "DevOps & Cloud", description: "Branching strategies, pull requests, rebasing, merge conflicts, and GitHub Actions.", moduleCount: 50 },
  { id: "golang", name: "Go (Golang) Developer", category: "Backend & Systems", description: "Goroutines, channels, interfaces, microservices, and high-concurrency systems.", moduleCount: 74, featured: true },
  { id: "graphql", name: "GraphQL Developer", category: "Backend & Systems", description: "Schemas, queries, mutations, resolvers, Apollo Server, and performance caching.", moduleCount: 48 },
  { id: "html", name: "HTML & Semantic Web", category: "Frontend & Web", description: "Semantic markup, accessibility (a11y), SEO tags, and modern Web APIs.", moduleCount: 38 },
  { id: "ios", name: "iOS Developer", category: "Mobile & Apps", description: "Swift, SwiftUI, UIKit, CoreData, Xcode, and App Store distribution.", moduleCount: 86 },
  { id: "java", name: "Java Developer", category: "Backend & Systems", description: "Java 21+, OOP, Spring Boot, JPA, multithreading, and microservices.", moduleCount: 94 },
  { id: "javascript", name: "JavaScript Mastery", category: "Frontend & Web", description: "ES6+, async/await, closures, prototypes, DOM manipulation, and V8 engine.", moduleCount: 88, featured: true },
  { id: "kotlin", name: "Kotlin Developer", category: "Mobile & Apps", description: "Coroutines, functional programming, Android development, and Multiplatform (KMP).", moduleCount: 70 },
  { id: "kubernetes", name: "Kubernetes Specialist", category: "DevOps & Cloud", description: "Pods, Deployments, Services, Helm charts, Ingress controllers, and CKA skills.", moduleCount: 82, featured: true },
  { id: "laravel", name: "Laravel Developer", category: "Backend & Systems", description: "PHP, Eloquent ORM, Blade templates, Queue workers, and SaaS boilerplates.", moduleCount: 68 },
  { id: "leetcode", name: "LeetCode & Problem Solving", category: "Architecture & CS", description: "Pattern-based coding interview prep: Two Pointers, Sliding Window, DP, Graphs.", moduleCount: 90 },
  { id: "linux", name: "Linux System Administrator", category: "DevOps & Cloud", description: "Bash, shell scripting, systemd, permissions, process management, and networking.", moduleCount: 86 },
  { id: "machine-learning", name: "Machine Learning Engineer", category: "AI & Data Science", description: "Scikit-Learn, PyTorch, TensorFlow, neural networks, feature engineering & MLOps.", moduleCount: 96, featured: true },
  { id: "mlops", name: "MLOps Specialist", category: "AI & Data Science", description: "Model deployment, MLflow, Kubeflow, feature stores, monitoring, and CI/CD for ML.", moduleCount: 72 },
  { id: "mongodb", name: "MongoDB Specialist", category: "Backend & Systems", description: "NoSQL document design, aggregation framework, indexing, and sharding.", moduleCount: 50 },
  { id: "nextjs", name: "Next.js & Server Components", category: "Frontend & Web", description: "App Router, SSR, SSG, Server Actions, middleware, and Vercel deployment.", moduleCount: 78, featured: true },
  { id: "nodejs", name: "Node.js Developer", category: "Backend & Systems", description: "Event loop, Express/Fastify, streams, NPM, async I/O, and microservices.", moduleCount: 85, featured: true },
  { id: "openclaw", name: "OpenClaw & Web Scrapers", category: "AI & Data Science", description: "Playwright, Puppeteer, headless browsers, DOM extraction, and web crawlers.", moduleCount: 52 },
  { id: "php", name: "Modern PHP", category: "Backend & Systems", description: "PHP 8+, Composer, OOP, PSR standards, attributes, and web security.", moduleCount: 62 },
  { id: "postgresql-dba", name: "PostgreSQL DBA", category: "Backend & Systems", description: "SQL tuning, indexing, EXPLAIN ANALYZE, replication, partitioning, and WAL.", moduleCount: 76 },
  { id: "product-design", name: "Product Designer", category: "Frontend & Web", description: "UI/UX, wireframing, prototyping, user testing, design systems, and Figma.", moduleCount: 70 },
  { id: "product-manager", name: "Product Manager", category: "Specialized Skill", description: "PRDs, roadmap prioritization, user metrics, customer discovery, and agile.", moduleCount: 66 },
  { id: "prompt-engineering", name: "Prompt Engineer", category: "AI & Data Science", description: "System prompts, Few-Shotting, Chain-of-Thought, ReAct, and guardrails.", moduleCount: 60, featured: true },
  { id: "python", name: "Python Developer", category: "Backend & Systems", description: "Language syntax, data structures, OOP, decorators, virtualenvs, and libraries.", moduleCount: 90, featured: true },
  { id: "qa", name: "QA Automation Engineer", category: "Security", description: "Selenium, Cypress, Playwright, Jest, API testing, and CI test automation.", moduleCount: 72 },
  { id: "react", name: "React Developer", category: "Frontend & Web", description: "Hooks, state management, TanStack Query, Virtual DOM, and component patterns.", moduleCount: 95, featured: true },
  { id: "react-native", name: "React Native Developer", category: "Mobile & Apps", description: "Expo, native bridges, mobile navigation, animated API, and app deployment.", moduleCount: 74 },
  { id: "redis", name: "Redis & Caching", category: "Backend & Systems", description: "Data structures, pub/sub, caching strategies, rate limiting, and persistence.", moduleCount: 48 },
  { id: "rust", name: "Rust Developer", category: "Backend & Systems", description: "Ownership, borrowing, lifetimes, Cargo, Tokio async, and WebAssembly.", moduleCount: 92, featured: true },
  { id: "shell-bash", name: "Shell / Bash Scripting", category: "DevOps & Cloud", description: "Scripting automation, pipes, awk/sed, environment variables, and cron.", moduleCount: 52 },
  { id: "software-architect", name: "Software Architect", category: "Architecture & CS", description: "Distributed systems, domain-driven design (DDD), trade-offs, and scaling.", moduleCount: 88, featured: true },
  { id: "sql", name: "SQL & Relational Databases", category: "Backend & Systems", description: "Complex joins, window functions, indexing, normal forms, and transaction isolation.", moduleCount: 70, featured: true },
  { id: "system-design", name: "System Design Masterclass", category: "Architecture & CS", description: "Scalable architecture, load balancers, caching, sharding, and real-time systems.", moduleCount: 95, featured: true },
  { id: "terraform", name: "Terraform & IaC", category: "DevOps & Cloud", description: "HCL syntax, modules, state management, provider configuration, and cloud automation.", moduleCount: 62 },
  { id: "typescript", name: "TypeScript Mastery", category: "Frontend & Web", description: "Generics, utility types, type narrowing, tsconfig, ASTs, and strict mode.", moduleCount: 82, featured: true },
  { id: "ux-design", name: "UX Designer", category: "Frontend & Web", description: "User research, information architecture, wireframing, and usability testing.", moduleCount: 60 },
  { id: "vibe-coding", name: "Vibe Coding & AI Pair Programming", category: "AI & Data Science", description: "Accelerated development using AI coding agents, prompt-driven UI, and auto-refactoring.", moduleCount: 50, featured: true },
  { id: "vue", name: "Vue.js Developer", category: "Frontend & Web", description: "Composition API, Pinia, Vue Router, Nuxt.js, and component patterns.", moduleCount: 68 },
];
