import { type Topic, type KnowledgeNode, type KnowledgeLink } from "./types";

export const TOPICS: Topic[] = [
  {
    id: "load-balancer",
    title: "Load Balancer",
    subtitle: "Distribute traffic across servers for reliability and scale",
    description: "A load balancer acts as the traffic cop for your system, distributing incoming requests across multiple servers to ensure no single server becomes overwhelmed. It's the foundation of horizontal scaling.",
    icon: "shuffle",
    difficulty: "beginner",
    duration: "15 min",
    companies: ["Netflix", "Amazon", "Google", "Facebook"],
    prerequisites: ["Basic networking knowledge"],
    sections: [
      {
        id: "what-is",
        title: "What is a Load Balancer?",
        type: "visual",
        content: "A load balancer sits between users and servers, distributing incoming requests across multiple backend servers. It handles health checks, SSL termination, and session persistence.",
        visual: {
          description: "Request flow through load balancer",
          nodes: [
            { id: "users", label: "Users", type: "user" },
            { id: "lb", label: "Load Balancer", type: "loadbalancer" },
            { id: "s1", label: "Server 1", type: "service" },
            { id: "s2", label: "Server 2", type: "service" },
            { id: "s3", label: "Server 3", type: "service" },
            { id: "db", label: "Database", type: "database" },
          ],
          edges: [
            { from: "users", to: "lb", label: "Requests", animated: true },
            { from: "lb", to: "s1", label: "33%", animated: true },
            { from: "lb", to: "s2", label: "33%", animated: true },
            { from: "lb", to: "s3", label: "33%", animated: true },
            { from: "s1", to: "db", label: "Read/Write" },
            { from: "s2", to: "db", label: "Read/Write" },
            { from: "s3", to: "db", label: "Read/Write" },
          ],
        },
      },
      {
        id: "story",
        title: "The Airport Analogy",
        type: "story",
        content: "Think of a load balancer like an airport check-in counter. Without it, all passengers crowd one counter (one server). With multiple counters, a coordinator directs passengers to the shortest line. If one counter closes, passengers go to others. This is exactly how load balancers work.",
        story: {
          context: "Imagine a busy airport with thousands of passengers.",
          analogy: "The load balancer is the flight coordinator directing passengers to the right counter.",
          transition: "Now let's see how this translates to server architecture.",
        },
      },
      {
        id: "algorithms",
        title: "Load Balancing Algorithms",
        type: "text",
        content: "Round Robin — Requests are distributed sequentially. Least Connections — Sends to the server with fewest active connections. IP Hash — Routes based on client IP for session persistence. Weighted Round Robin — Servers with higher capacity get more traffic. Each algorithm suits different use cases.",
      },
      {
        id: "types",
        title: "Types of Load Balancers",
        type: "comparison",
        content: "Hardware vs Software vs Cloud load balancers each have distinct tradeoffs in cost, flexibility, and maintenance.",
      },
    ],
    quiz: [
      {
        id: "lb-q1",
        question: "What is the primary purpose of a load balancer?",
        options: ["Store data persistently", "Distribute traffic across servers", "Compress images", "Manage user authentication"],
        correctIndex: 1,
        explanation: "Load balancers distribute incoming network traffic across multiple servers to ensure reliability and prevent overload.",
        difficulty: "easy",
      },
      {
        id: "lb-q2",
        question: "Which load balancing algorithm sends requests to the server with fewest active connections?",
        options: ["Round Robin", "IP Hash", "Least Connections", "Random"],
        correctIndex: 2,
        explanation: "Least Connections routing sends traffic to the server currently handling the fewest active connections.",
        difficulty: "medium",
      },
      {
        id: "lb-q3",
        question: "What is a key benefit of load balancers for scalability?",
        options: ["Faster CPU speeds", "Horizontal scaling", "Vertical scaling only", "Reduced memory usage"],
        correctIndex: 1,
        explanation: "Load balancers enable horizontal scaling by distributing traffic across added servers seamlessly.",
        difficulty: "easy",
      },
    ],
    architecture: {
      description: "Standard load-balanced architecture",
      nodes: [
        { id: "users", label: "Clients", type: "user" },
        { id: "dns", label: "DNS", type: "service" },
        { id: "lb", label: "Load Balancer", type: "loadbalancer" },
        { id: "app1", label: "App Server 1", type: "service" },
        { id: "app2", label: "App Server 2", type: "service" },
        { id: "app3", label: "App Server 3", type: "service" },
        { id: "cache", label: "Redis Cache", type: "cache" },
        { id: "db", label: "Primary DB", type: "database" },
        { id: "db-replica", label: "Read Replica", type: "database" },
      ],
      edges: [
        { from: "users", to: "dns", label: "lookup", animated: true },
        { from: "users", to: "lb", animated: true },
        { from: "lb", to: "app1", animated: true },
        { from: "lb", to: "app2", animated: true },
        { from: "lb", to: "app3", animated: true },
        { from: "app1", to: "cache" },
        { from: "app2", to: "cache" },
        { from: "app3", to: "cache" },
        { from: "app1", to: "db" },
        { from: "app2", to: "db" },
        { from: "app3", to: "db" },
        { from: "db", to: "db-replica" },
      ],
    },
    comparisons: [
      {
        title: "Load Balancer Algorithms",
        items: [
          { name: "Round Robin", icon: "refresh-cw", pros: ["Simple to implement", "Fair distribution", "Low overhead"], cons: ["Ignores server load", "No session awareness", "Unequal if server specs differ"], useCases: ["Identical server specs", "Stateless applications", "Simple setups"] },
          { name: "Least Connections", icon: "activity", pros: ["Adapts to load", "Better resource use", "Handles varying request times"], cons: ["More complex", "Requires connection tracking", "Higher memory usage"], useCases: ["Long-lived connections", "Variable request processing", "WebSocket servers"] },
          { name: "IP Hash", icon: "hash", pros: ["Session persistence", "No session store needed", "Deterministic routing"], cons: ["Uneven distribution", "Client IP changes break", "Not ideal for autoscaling"], useCases: ["Sticky sessions", "Stateful applications", "Shopping carts"] },
        ],
      },
    ],
    caseStudies: [
      {
        company: "Netflix",
        title: "Netflix's Multi-Region Load Balancing",
        description: "Netflix uses AWS Elastic Load Balancers across multiple regions. Their custom solution routes traffic based on region, availability zone, and real-time server health. They use DNS-based routing at the top level and internal LBs within each region.",
        architecture: {
          description: "Netflix multi-region LB architecture",
          nodes: [
            { id: "users", label: "Users", type: "user" },
            { id: "dns", label: "Route53 DNS", type: "service" },
            { id: "lb-us", label: "US ELB", type: "loadbalancer" },
            { id: "lb-eu", label: "EU ELB", type: "loadbalancer" },
            { id: "us-app", label: "US App Cluster", type: "service" },
            { id: "eu-app", label: "EU App Cluster", type: "service" },
            { id: "us-cache", label: "US Cache", type: "cache" },
            { id: "eu-cache", label: "EU Cache", type: "cache" },
          ],
          edges: [
            { from: "users", to: "dns", animated: true },
            { from: "dns", to: "lb-us", animated: true },
            { from: "dns", to: "lb-eu", animated: true },
            { from: "lb-us", to: "us-app", animated: true },
            { from: "lb-eu", to: "eu-app", animated: true },
            { from: "us-app", to: "us-cache" },
            { from: "eu-app", to: "eu-cache" },
          ],
        },
      },
    ],
  },
  {
    id: "caching",
    title: "Caching",
    subtitle: "Store frequently accessed data for lightning-fast retrieval",
    description: "Caching stores copies of frequently accessed data in a high-speed storage layer. When data is requested, the cache is checked first — if found (cache hit), it's returned instantly. If not (cache miss), it's fetched from the slower source and stored for next time.",
    icon: "zap",
    difficulty: "beginner",
    duration: "20 min",
    companies: ["Google", "Twitter", "Reddit", "Cloudflare"],
    prerequisites: ["Basic understanding of databases"],
    sections: [
      {
        id: "what-is",
        title: "What is Caching?",
        type: "visual",
        content: "A cache is a high-speed data storage layer that stores a subset of data, typically transient in nature. Caches reduce latency and improve read throughput by serving data from fast memory instead of slower disk-based storage.",
        visual: {
          description: "Cache request flow — hit vs miss",
          nodes: [
            { id: "user", label: "User Request", type: "user" },
            { id: "lb", label: "Load Balancer", type: "loadbalancer" },
            { id: "app", label: "Application", type: "service" },
            { id: "cache", label: "Cache Layer", type: "cache" },
            { id: "db", label: "Database", type: "database" },
          ],
          edges: [
            { from: "user", to: "lb", animated: true },
            { from: "lb", to: "app", animated: true },
            { from: "app", to: "cache", label: "1. Check Cache", animated: true },
            { from: "cache", to: "app", label: "2a. Hit → Return", animated: true },
            { from: "app", to: "db", label: "2b. Miss → Query DB" },
            { from: "db", to: "app", label: "3. Return + Store in Cache" },
            { from: "app", to: "user", label: "Response" },
          ],
        },
      },
      {
        id: "story",
        title: "The Librarian Story",
        type: "story",
        content: "A librarian keeps popular books on a shelf near the front desk. When someone asks for a book, she checks the nearby shelf first. If it's there, she hands it over instantly — that's a cache hit. If not, she walks to the storage room to get it — a cache miss — but then leaves a copy on the shelf for next time.",
        story: {
          context: "A librarian serves hundreds of visitors daily at a busy library.",
          analogy: "The 'popular books shelf' is your cache — frequently accessed data stored close at hand.",
          transition: "Now let's see how this principle powers modern web applications.",
        },
      },
      {
        id: "strategies",
        title: "Caching Strategies",
        type: "text",
        content: "Cache-Aside — Application checks cache first, then database on miss. Write-Through — Data written to cache and DB simultaneously. Write-Behind — Data written to cache, then asynchronously to DB. Cache eviction policies include LRU (Least Recently Used), LFU (Least Frequently Used), and TTL (Time-To-Live).",
      },
      {
        id: "levels",
        title: "Cache Levels",
        type: "comparison",
        content: "Caching can happen at multiple layers: Browser Cache (local storage), CDN Cache (geographic edge nodes), Application Cache (in-memory caches like Redis), Database Cache (query result caching). Each layer has different latency characteristics and use cases.",
      },
    ],
    quiz: [
      {
        id: "cache-q1",
        question: "What happens on a cache hit?",
        options: ["Data is fetched from database", "Data is returned from cache", "Cache is cleared", "New cache entry created"],
        correctIndex: 1,
        explanation: "On a cache hit, the requested data is found in the cache and returned immediately, skipping the slower database lookup.",
        difficulty: "easy",
      },
      {
        id: "cache-q2",
        question: "Which cache eviction policy removes the oldest unused entries?",
        options: ["LFU", "TTL", "LRU", "FIFO"],
        correctIndex: 2,
        explanation: "LRU (Least Recently Used) evicts items that haven't been accessed for the longest time.",
        difficulty: "medium",
      },
      {
        id: "cache-q3",
        question: "Why is cache invalidation considered hard in distributed systems?",
        options: ["Caches are too slow", "Multiple cache nodes must be updated atomically", "Disk space is limited", "Network latency"],
        correctIndex: 1,
        explanation: "In distributed systems, keeping all cache nodes consistent when data changes requires complex coordination.",
        difficulty: "hard",
      },
    ],
    architecture: {
      description: "Multi-layer caching architecture",
      nodes: [
        { id: "browser", label: "Browser Cache", type: "cache" },
        { id: "cdn", label: "CDN Edge", type: "cdn" },
        { id: "lb", label: "Load Balancer", type: "loadbalancer" },
        { id: "app", label: "App Server", type: "service" },
        { id: "redis", label: "Redis Cluster", type: "cache" },
        { id: "db", label: "Database", type: "database" },
        { id: "origin", label: "Origin Server", type: "service" },
      ],
      edges: [
        { from: "browser", to: "cdn", animated: true },
        { from: "cdn", to: "lb", animated: true },
        { from: "lb", to: "app", animated: true },
        { from: "app", to: "redis", animated: true },
        { from: "app", to: "db" },
        { from: "cdn", to: "origin" },
      ],
    },
  },
  {
    id: "databases",
    title: "SQL vs NoSQL",
    subtitle: "Choose the right database for your data's shape and scale",
    description: "SQL databases store structured data in tables with predefined schemas and relationships. NoSQL databases offer flexible schemas optimized for specific data models like documents, key-values, graphs, or columns. The choice depends on your consistency needs, scale requirements, and data shape.",
    icon: "database",
    difficulty: "beginner",
    duration: "25 min",
    companies: ["Uber", "Airbnb", "Meta", "Twitter"],
    prerequisites: ["Basic data concepts"],
    sections: [
      {
        id: "overview",
        title: "SQL vs NoSQL",
        type: "comparison",
        content: "SQL databases excel at complex queries and strict consistency. NoSQL databases excel at horizontal scaling and flexible schemas.",
      },
      {
        id: "story",
        title: "The Filing Cabinet vs Storage Unit",
        type: "story",
        content: "SQL is like a filing cabinet — every file in its labeled folder with strict rules. NoSQL is like a storage unit — you can store anything: boxes, furniture, artwork. The filing cabinet makes finding specific records easy; the storage unit gives you unlimited flexibility.",
        story: {
          context: "Running a business that needs to store information about customers.",
          analogy: "SQL = perfectly organized filing cabinet. NoSQL = spacious storage unit with flexible organization.",
          transition: "Let's examine the technical tradeoffs in detail.",
        },
      },
      {
        id: "when-to-use",
        title: "When to Use Each",
        type: "text",
        content: "Use SQL when: data is structured, relationships are complex, ACID compliance is required, and queries involve joins. Use NoSQL when: data is semi-structured or unstructured, you need horizontal scaling, rapid iteration on schema, or high write throughput.",
      },
    ],
    quiz: [
      {
        id: "db-q1",
        question: "Which property guarantees that database transactions are processed reliably?",
        options: ["CRUD", "ACID", "BASE", "JSON"],
        correctIndex: 1,
        explanation: "ACID (Atomicity, Consistency, Isolation, Durability) guarantees reliable transaction processing.",
        difficulty: "medium",
      },
      {
        id: "db-q2",
        question: "When would you choose a NoSQL database over SQL?",
        options: ["Complex joins required", "Strict ACID compliance", "Flexible schema needed", "Fixed data structure"],
        correctIndex: 2,
        explanation: "NoSQL databases are ideal when you need flexible schemas and rapid iteration on data models.",
        difficulty: "easy",
      },
      {
        id: "db-q3",
        question: "What is the CAP theorem about?",
        options: ["Consistency, Availability, Partition Tolerance", "Compute, Access, Persist", "Cache, Aggregate, Partition", "Create, Append, Protect"],
        correctIndex: 0,
        explanation: "CAP theorem states a distributed system can only guarantee two of: Consistency, Availability, and Partition Tolerance.",
        difficulty: "hard",
      },
    ],
    architecture: {
      description: "Hybrid SQL + NoSQL architecture",
      nodes: [
        { id: "app", label: "Application", type: "service" },
        { id: "postgres", label: "PostgreSQL", type: "database" },
        { id: "mongo", label: "MongoDB", type: "database" },
        { id: "redis", label: "Redis Cache", type: "cache" },
        { id: "es", label: "Elasticsearch", type: "service" },
        { id: "queue", label: "Message Queue", type: "queue" },
      ],
      edges: [
        { from: "app", to: "postgres", label: "Orders, Users" },
        { from: "app", to: "mongo", label: "Product Catalog" },
        { from: "app", to: "redis", label: "Sessions" },
        { from: "app", to: "es", label: "Search Index" },
        { from: "app", to: "queue" },
      ],
    },
    comparisons: [
      {
        title: "SQL vs NoSQL",
        items: [
          { name: "SQL", icon: "grid", pros: ["Strong consistency", "Complex queries with joins", "Strict schema enforcement", "Mature ecosystem"], cons: ["Vertical scaling limits", "Rigid schema changes", "Less performant at scale"], useCases: ["Financial systems", "ERP/CRM", "E-commerce orders"] },
          { name: "NoSQL", icon: "layers", pros: ["Horizontal scaling", "Flexible schemas", "High write throughput", "Fast prototyping"], cons: ["Eventual consistency", "Limited complex queries", "Less mature tooling"], useCases: ["Real-time analytics", "IoT data", "Content management", "User profiles"] },
        ],
      },
    ],
    caseStudies: [
      {
        company: "Uber",
        title: "Uber's Polyglot Database Strategy",
        description: "Uber uses multiple databases for different needs: MySQL for core trip data (ACID compliance), Cassandra for real-time driver location (high write throughput), Redis for surge pricing (low-latency), and Elasticsearch for search.",
        architecture: {
          description: "Uber's database stack",
          nodes: [
            { id: "app", label: "Uber App", type: "service" },
            { id: "mysql", label: "MySQL (Trips)", type: "database" },
            { id: "cass", label: "Cassandra (Location)", type: "database" },
            { id: "redis", label: "Redis (Pricing)", type: "cache" },
            { id: "es", label: "Elasticsearch", type: "service" },
            { id: "kafka", label: "Kafka (Events)", type: "queue" },
          ],
          edges: [
            { from: "app", to: "mysql", animated: true },
            { from: "app", to: "cass", animated: true },
            { from: "app", to: "redis", animated: true },
            { from: "app", to: "es", animated: true },
            { from: "app", to: "kafka" },
          ],
        },
      },
    ],
  },
  {
    id: "cdn",
    title: "Content Delivery Network",
    subtitle: "Serve content from edge locations near your users",
    description: "A CDN is a geographically distributed network of proxy servers that cache static and dynamic content. When a user requests content, it's served from the nearest edge server, drastically reducing latency and offloading traffic from origin servers.",
    icon: "globe",
    difficulty: "beginner",
    duration: "12 min",
    companies: ["Cloudflare", "Akamai", "AWS CloudFront", "Fastly"],
    prerequisites: ["Basic networking"],
    sections: [
      {
        id: "what-is",
        title: "What is a CDN?",
        type: "visual",
        content: "A CDN places servers at edge locations worldwide. When a user requests content, DNS routes them to the nearest edge server. If the edge has the content cached, it's served immediately (edge hit). If not, the edge fetches from origin, caches it, and serves.",
        visual: {
          description: "CDN request routing across global edge nodes",
          nodes: [
            { id: "user", label: "User", type: "user" },
            { id: "dns", label: "DNS", type: "service" },
            { id: "edge-us", label: "US Edge", type: "cdn" },
            { id: "edge-eu", label: "EU Edge", type: "cdn" },
            { id: "edge-asia", label: "Asia Edge", type: "cdn" },
            { id: "origin", label: "Origin Server", type: "service" },
          ],
          edges: [
            { from: "user", to: "dns", animated: true },
            { from: "dns", to: "edge-us", animated: true },
            { from: "edge-us", to: "origin" },
            { from: "edge-eu", to: "origin" },
            { from: "edge-asia", to: "origin" },
          ],
        },
      },
      {
        id: "benefits",
        title: "Key Benefits",
        type: "text",
        content: "Reduced latency — content travels shorter distances. Reduced origin load — edge servers handle requests. DDoS protection — CDN absorbs attack traffic. High availability — if one edge goes down, others take over. Global reach — serve users anywhere with consistent speed.",
      },
    ],
    quiz: [
      {
        id: "cdn-q1",
        question: "What is the primary purpose of a CDN?",
        options: ["Store backups", "Reduce latency by serving from edge", "Compress videos", "Manage DNS"],
        correctIndex: 1,
        explanation: "CDNs reduce latency by serving content from geographically distributed edge servers close to users.",
        difficulty: "easy",
      },
      {
        id: "cdn-q2",
        question: "What happens on a CDN cache miss?",
        options: ["User gets 404 error", "Edge fetches from origin and caches it", "Request is dropped", "Cache is cleared"],
        correctIndex: 1,
        explanation: "On a cache miss, the edge server fetches content from the origin server, caches it for future requests, and serves it to the user.",
        difficulty: "medium",
      },
    ],
    architecture: {
      description: "Global CDN edge network",
      nodes: [
        { id: "client", label: "Client", type: "user" },
        { id: "edge1", label: "Edge (NA)", type: "cdn" },
        { id: "edge2", label: "Edge (EU)", type: "cdn" },
        { id: "edge3", label: "Edge (APAC)", type: "cdn" },
        { id: "origin", label: "Origin", type: "service" },
        { id: "lb", label: "Origin LB", type: "loadbalancer" },
        { id: "app", label: "App Server", type: "service" },
      ],
      edges: [
        { from: "client", to: "edge1", animated: true },
        { from: "edge1", to: "origin" },
        { from: "edge2", to: "origin" },
        { from: "edge3", to: "origin" },
        { from: "origin", to: "lb" },
        { from: "lb", to: "app" },
      ],
    },
  },
  {
    id: "message-queues",
    title: "Message Queues",
    subtitle: "Decouple services with async communication",
    description: "Message queues enable asynchronous communication between services. Producers send messages to a queue, and consumers process them at their own pace. This decouples services, enables buffering during traffic spikes, and improves overall system reliability.",
    icon: "inbox",
    difficulty: "intermediate",
    duration: "18 min",
    companies: ["Uber", "Netflix", "LinkedIn", "Twitter"],
    prerequisites: ["Microservices concept", "Async programming basics"],
    sections: [
      {
        id: "what-is",
        title: "What is a Message Queue?",
        type: "visual",
        content: "A message queue stores messages between producers and consumers. Producers write messages without waiting for consumers. Consumers read messages at their own pace. This decouples the system — if a consumer goes down, messages queue up until it recovers.",
        visual: {
          description: "Pub/sub architecture with message queue",
          nodes: [
            { id: "producer", label: "Producer", type: "service" },
            { id: "queue", label: "Message Queue", type: "queue" },
            { id: "consumer1", label: "Consumer 1", type: "service" },
            { id: "consumer2", label: "Consumer 2", type: "service" },
            { id: "consumer3", label: "Consumer 3", type: "service" },
            { id: "db", label: "Database", type: "database" },
          ],
          edges: [
            { from: "producer", to: "queue", label: "Publish", animated: true },
            { from: "queue", to: "consumer1", label: "Consume", animated: true },
            { from: "queue", to: "consumer2", label: "Consume", animated: true },
            { from: "queue", to: "consumer3", label: "Consume", animated: true },
            { from: "consumer1", to: "db" },
            { from: "consumer2", to: "db" },
            { from: "consumer3", to: "db" },
          ],
        },
      },
      {
        id: "story",
        title: "The Restaurant Kitchen",
        type: "story",
        content: "In a restaurant kitchen, the expediting rack holds orders. Chefs (producers) put completed dishes on the rack. Waiters (consumers) pick them up when ready to serve. If no waiter is available, dishes stay on the rack — nothing is lost. The rack decouples chefs from waiters.",
        story: {
          context: "A busy restaurant kitchen during dinner rush.",
          analogy: "The expediting rack is your message queue. Chefs = producers, Waiters = consumers.",
          transition: "This same pattern applies to distributed systems at scale.",
        },
      },
      {
        id: "patterns",
        title: "Common Patterns",
        type: "text",
        content: "Work Queues — Distribute tasks among workers. Pub/Sub — One message to multiple consumers. Event Sourcing — Store events as the source of truth. Dead Letter Queues — Handle failed messages gracefully. Each pattern solves a different async communication challenge.",
      },
    ],
    quiz: [
      {
        id: "mq-q1",
        question: "What is the main benefit of message queues?",
        options: ["Faster database queries", "Decoupling services", "Better encryption", "Static file serving"],
        correctIndex: 1,
        explanation: "Message queues decouple services by enabling asynchronous communication, so producers and consumers operate independently.",
        difficulty: "easy",
      },
      {
        id: "mq-q2",
        question: "What is a dead letter queue?",
        options: ["Queue for deleted messages", "Queue for failed messages", "Queue with no consumers", "FIFO queue"],
        correctIndex: 1,
        explanation: "A dead letter queue stores messages that failed to process, preventing data loss and allowing later analysis.",
        difficulty: "medium",
      },
    ],
    architecture: {
      description: "Event-driven architecture with Kafka",
      nodes: [
        { id: "web", label: "Web App", type: "service" },
        { id: "api", label: "API Gateway", type: "gateway" },
        { id: "kafka", label: "Kafka Cluster", type: "queue" },
        { id: "email", label: "Email Service", type: "service" },
        { id: "analytics", label: "Analytics", type: "service" },
        { id: "notif", label: "Notifications", type: "service" },
        { id: "db", label: "Database", type: "database" },
      ],
      edges: [
        { from: "web", to: "api", animated: true },
        { from: "api", to: "kafka", label: "events", animated: true },
        { from: "kafka", to: "email", animated: true },
        { from: "kafka", to: "analytics", animated: true },
        { from: "kafka", to: "notif", animated: true },
        { from: "email", to: "db" },
        { from: "analytics", to: "db" },
      ],
    },
  },
  {
    id: "api-gateway",
    title: "API Gateway",
    subtitle: "Single entry point for all client requests",
    description: "An API gateway is a server that acts as the single entry point for all client requests. It routes requests to appropriate microservices, handles authentication, rate limiting, request transformation, and response aggregation. Clients don't need to know the internal service topology.",
    icon: "shield",
    difficulty: "intermediate",
    duration: "15 min",
    companies: ["Amazon", "Netflix", "Shopify", "Kong"],
    prerequisites: ["Microservices", "REST APIs"],
    sections: [
      {
        id: "what-is",
        title: "What is an API Gateway?",
        type: "visual",
        content: "An API gateway sits between clients and microservices. Instead of clients calling multiple services directly, they call the gateway, which handles routing, authentication, rate limiting, and protocol translation.",
        visual: {
          description: "API Gateway routing to backend services",
          nodes: [
            { id: "client", label: "Client Apps", type: "user" },
            { id: "gw", label: "API Gateway", type: "gateway" },
            { id: "auth", label: "Auth Service", type: "service" },
            { id: "users", label: "User Service", type: "service" },
            { id: "orders", label: "Order Service", type: "service" },
            { id: "payments", label: "Payment Service", type: "service" },
            { id: "notif", label: "Notification", type: "service" },
          ],
          edges: [
            { from: "client", to: "gw", animated: true },
            { from: "gw", to: "auth", animated: true },
            { from: "gw", to: "users", animated: true },
            { from: "gw", to: "orders", animated: true },
            { from: "gw", to: "payments", animated: true },
            { from: "gw", to: "notif", animated: true },
          ],
        },
      },
      {
        id: "features",
        title: "Key Features",
        type: "text",
        content: "Authentication — Centralized auth checks. Rate Limiting — Per-client traffic control. Request Transformation — Convert protocols (REST→gRPC). Response Aggregation — Combine multiple service responses. Circuit Breaking — Fail fast when downstream services are down.",
      },
    ],
    quiz: [
      {
        id: "gw-q1",
        question: "What problem does an API gateway solve?",
        options: ["Database connection pooling", "Clients knowing internal service topology", "File storage", "CSS bundling"],
        correctIndex: 1,
        explanation: "API gateways abstract internal service topology from clients, providing a single entry point.",
        difficulty: "medium",
      },
    ],
    architecture: {
      description: "API Gateway in microservices architecture",
      nodes: [
        { id: "mobile", label: "Mobile App", type: "user" },
        { id: "web", label: "Web App", type: "user" },
        { id: "gw", label: "API Gateway", type: "gateway" },
        { id: "svc1", label: "Service A", type: "service" },
        { id: "svc2", label: "Service B", type: "service" },
        { id: "svc3", label: "Service C", type: "service" },
        { id: "redis", label: "Redis", type: "cache" },
      ],
      edges: [
        { from: "mobile", to: "gw", animated: true },
        { from: "web", to: "gw", animated: true },
        { from: "gw", to: "svc1", animated: true },
        { from: "gw", to: "svc2", animated: true },
        { from: "gw", to: "svc3", animated: true },
        { from: "svc1", to: "redis" },
        { from: "svc2", to: "redis" },
      ],
    },
  },
  {
    id: "microservices",
    title: "Microservices Architecture",
    subtitle: "Build applications as a suite of independently deployable services",
    description: "Microservices architecture structures an application as a collection of loosely coupled, independently deployable services. Each service owns its data, runs its own process, and communicates via well-defined APIs. This enables autonomous teams, independent scaling, and technology diversity.",
    icon: "box",
    difficulty: "intermediate",
    duration: "25 min",
    companies: ["Netflix", "Amazon", "Uber", "Spotify"],
    prerequisites: ["Monolithic architecture", "REST/gRPC", "Docker basics"],
    sections: [
      {
        id: "what-is",
        title: "What is Microservices?",
        type: "visual",
        content: "Instead of one giant application (monolith), microservices split functionality into small, independent services. Each service has its own database, can be deployed independently, and is owned by a small team.",
        visual: {
          description: "Monolith vs Microservices comparison",
          nodes: [
            { id: "monolith", label: "Monolith App", type: "service" },
            { id: "mono-db", label: "Single DB", type: "database" },
            { id: "svc-a", label: "Auth Service", type: "service" },
            { id: "svc-b", label: "Catalog Service", type: "service" },
            { id: "svc-c", label: "Order Service", type: "service" },
            { id: "svc-d", label: "Payment Service", type: "service" },
            { id: "db-a", label: "Auth DB", type: "database" },
            { id: "db-b", label: "Catalog DB", type: "database" },
            { id: "db-c", label: "Order DB", type: "database" },
            { id: "db-d", label: "Payment DB", type: "database" },
          ],
          edges: [
            { from: "monolith", to: "mono-db" },
            { from: "svc-a", to: "db-a" },
            { from: "svc-b", to: "db-b" },
            { from: "svc-c", to: "db-c" },
            { from: "svc-d", to: "db-d" },
          ],
        },
      },
      {
        id: "story",
        title: "The Food Court",
        type: "story",
        content: "A food court has independent stalls — pizza, burgers, sushi, tacos. Each runs independently with its own kitchen. If the pizza stall closes, the rest stay open. One stall can upgrade its menu without affecting others. That's microservices. A single restaurant is a monolith — if the kitchen floods, everything closes.",
        story: {
          context: "A shopping mall food court serving thousands daily.",
          analogy: "Independent food stalls = microservices. Single restaurant = monolith.",
          transition: "Let's explore the architectural tradeoffs.",
        },
      },
      {
        id: "challenges",
        title: "Key Challenges",
        type: "text",
        content: "Service Discovery — Services need to find each other. Data Consistency — Each service owns its data, making transactions complex. Network Latency — Remote calls replace in-process calls. Observability — Monitoring and debugging across services. Deployment Complexity — Coordinating releases across services.",
      },
    ],
    quiz: [
      {
        id: "ms-q1",
        question: "What is a key characteristic of microservices?",
        options: ["Shared database for all services", "Independent deployability", "Single codebase", "Tight coupling"],
        correctIndex: 1,
        explanation: "Microservices are independently deployable — each service can be updated without affecting others.",
        difficulty: "easy",
      },
      {
        id: "ms-q2",
        question: "Which pattern helps microservices find each other?",
        options: ["API Gateway", "Service Discovery", "Database per Service", "Event Sourcing"],
        correctIndex: 1,
        explanation: "Service Discovery enables microservices to dynamically locate each other's network addresses.",
        difficulty: "medium",
      },
    ],
    architecture: {
      description: "Microservices deployment architecture",
      nodes: [
        { id: "gw", label: "API Gateway", type: "gateway" },
        { id: "svc1", label: "Auth Service", type: "service" },
        { id: "svc2", label: "Catalog", type: "service" },
        { id: "svc3", label: "Orders", type: "service" },
        { id: "svc4", label: "Payments", type: "service" },
        { id: "svc5", label: "Notifications", type: "service" },
        { id: "queue", label: "Message Bus", type: "queue" },
        { id: "db1", label: "Auth DB", type: "database" },
        { id: "db2", label: "Catalog DB", type: "database" },
        { id: "db3", label: "Orders DB", type: "database" },
      ],
      edges: [
        { from: "gw", to: "svc1", animated: true },
        { from: "gw", to: "svc2", animated: true },
        { from: "gw", to: "svc3", animated: true },
        { from: "gw", to: "svc4", animated: true },
        { from: "gw", to: "svc5", animated: true },
        { from: "svc1", to: "db1" },
        { from: "svc2", to: "db2" },
        { from: "svc3", to: "db3" },
        { from: "svc3", to: "queue" },
        { from: "svc4", to: "queue" },
        { from: "svc5", to: "queue" },
      ],
    },
    comparisons: [
      {
        title: "Monolith vs Microservices",
        items: [
          { name: "Monolith", icon: "box", pros: ["Simple development", "Easy debugging", "Low latency", "Atomic deployments"], cons: ["Tight coupling", "Scaling entire app", "Technology lock-in", "Slow iteration"], useCases: ["Startups", "Simple applications", "Small teams"] },
          { name: "Microservices", icon: "layers", pros: ["Independent scaling", "Technology diversity", "Faster deployments", "Team autonomy"], cons: ["Distributed complexity", "Network latency", "Data consistency", "Operational overhead"], useCases: ["Large applications", "Multiple teams", "Rapid scaling needs"] },
        ],
      },
    ],
  },
  {
    id: "consistent-hashing",
    title: "Consistent Hashing",
    subtitle: "Distribute data evenly while minimizing reshuffling",
    description: "Consistent Hashing is a distributed hashing scheme that minimizes key remapping when the number of hash slots changes. Unlike traditional modulo hashing where adding/removing a node requires remapping almost all keys, consistent hashing only remaps K/N keys on average.",
    icon: "hash",
    difficulty: "advanced",
    duration: "20 min",
    companies: ["Amazon DynamoDB", "Cassandra", "Discord", "Akamai"],
    prerequisites: ["Hash functions", "Distributed systems basics"],
    sections: [
      {
        id: "what-is",
        title: "What is Consistent Hashing?",
        type: "visual",
        content: "Place hash values on a circle (hash ring). Each server is assigned positions on the ring. Each key is hashed and assigned to the nearest server clockwise. When a server is added or removed, only keys in that server's region need to be remapped.",
        visual: {
          description: "Consistent hashing ring",
          nodes: [
            { id: "ring", label: "Hash Ring", type: "service" },
            { id: "s1", label: "Server A", type: "service" },
            { id: "s2", label: "Server B", type: "service" },
            { id: "s3", label: "Server C", type: "service" },
            { id: "s4", label: "Server D", type: "service" },
            { id: "key1", label: "Key → A", type: "database" },
            { id: "key2", label: "Key → B", type: "database" },
            { id: "key3", label: "Key → C", type: "database" },
            { id: "key4", label: "Key → D", type: "database" },
          ],
          edges: [
            { from: "key1", to: "s1" },
            { from: "key2", to: "s2" },
            { from: "key3", to: "s3" },
            { from: "key4", to: "s4" },
          ],
        },
      },
      {
        id: "story",
        title: "The Round Table",
        type: "story",
        content: "Imagine a round table with servers seated around it. Each key finds the nearest server clockwise. When a new server sits at the table, it only takes keys between it and the next server — the rest stays put. When a server leaves, only their immediate neighbors need to handle the extra load.",
        story: {
          context: "A round table with dynamically arriving and leaving guests.",
          analogy: "Seats = server positions. Guests = data keys. Clockwise nearest = assignment rule.",
          transition: "This elegant solution powers some of the largest distributed systems.",
        },
      },
      {
        id: "virtual-nodes",
        title: "Virtual Nodes",
        type: "text",
        content: "To handle uneven distribution, consistent hashing uses virtual nodes — each physical server appears multiple times on the ring. This spreads keys more evenly and reduces the impact of server additions or removals. DynamoDB uses this extensively.",
      },
    ],
    quiz: [
      {
        id: "ch-q1",
        question: "What problem does consistent hashing solve?",
        options: ["Slow database queries", "Minimizing key remapping when nodes change", "Faster network routing", "Data encryption"],
        correctIndex: 1,
        explanation: "Consistent hashing minimizes the number of keys that must be remapped when servers are added or removed.",
        difficulty: "hard",
      },
      {
        id: "ch-q2",
        question: "What is the purpose of virtual nodes?",
        options: ["Reduce memory usage", "Improve distribution balance", "Faster hash computation", "Network compression"],
        correctIndex: 1,
        explanation: "Virtual nodes (vnodes) improve load distribution by representing each physical server at multiple points on the hash ring.",
        difficulty: "hard",
      },
    ],
    architecture: {
      description: "Distributed cache with consistent hashing",
      nodes: [
        { id: "client", label: "Client", type: "user" },
        { id: "lb", label: "Load Balancer", type: "loadbalancer" },
        { id: "app", label: "Application", type: "service" },
        { id: "ring", label: "Hash Ring", type: "service" },
        { id: "node1", label: "Cache Node 1", type: "cache" },
        { id: "node2", label: "Cache Node 2", type: "cache" },
        { id: "node3", label: "Cache Node 3", type: "cache" },
        { id: "node4", label: "Cache Node 4", type: "cache" },
      ],
      edges: [
        { from: "client", to: "lb", animated: true },
        { from: "lb", to: "app", animated: true },
        { from: "app", to: "ring", animated: true },
        { from: "ring", to: "node1" },
        { from: "ring", to: "node2" },
        { from: "ring", to: "node3" },
        { from: "ring", to: "node4" },
      ],
    },
  },
  {
    id: "rate-limiting",
    title: "Rate Limiting",
    subtitle: "Control traffic flow to protect your services",
    description: "Rate limiting controls the rate of requests a client can make to an API within a time window. It prevents abuse, ensures fair usage, protects backend services from overload, and helps maintain quality of service for all users.",
    icon: "gauge",
    difficulty: "intermediate",
    duration: "15 min",
    companies: ["Twitter", "GitHub", "Stripe", "Google"],
    prerequisites: ["API design", "Data structures"],
    sections: [
      {
        id: "what-is",
        title: "What is Rate Limiting?",
        type: "visual",
        content: "Rate limiting tracks each client's request count within a time window. If a client exceeds the limit, subsequent requests are rejected with 429 Too Many Requests. Different clients can have different limits based on their plan.",
        visual: {
          description: "Rate limit enforcement",
          nodes: [
            { id: "client1", label: "Free User", type: "user" },
            { id: "client2", label: "Premium User", type: "user" },
            { id: "client3", label: "Abusive Client", type: "user" },
            { id: "gw", label: "API Gateway", type: "gateway" },
            { id: "counter", label: "Rate Limiter", type: "service" },
            { id: "redis", label: "Redis Counter", type: "cache" },
            { id: "api", label: "API Server", type: "service" },
          ],
          edges: [
            { from: "client1", to: "gw", label: "100 req/min", animated: true },
            { from: "client2", to: "gw", label: "1000 req/min", animated: true },
            { from: "client3", to: "gw", label: "BLOCKED ✗", animated: true },
            { from: "gw", to: "counter" },
            { from: "counter", to: "redis" },
            { from: "gw", to: "api", animated: true },
          ],
        },
      },
      {
        id: "algorithms",
        title: "Rate Limiting Algorithms",
        type: "text",
        content: "Token Bucket — Tokens added at fixed rate; each request consumes one. Leaky Bucket — Requests processed at fixed rate; excess spills. Sliding Window — Counts requests in a rolling time window. Fixed Window — Resets counter at window boundaries (simpler but allows bursts).",
      },
    ],
    quiz: [
      {
        id: "rl-q1",
        question: "What HTTP status code indicates rate limiting?",
        options: ["503", "429", "401", "500"],
        correctIndex: 1,
        explanation: "HTTP 429 Too Many Requests is returned when a client exceeds the rate limit.",
        difficulty: "easy",
      },
      {
        id: "rl-q2",
        question: "Which algorithm permits smooth request flow by adding tokens at a fixed rate?",
        options: ["Fixed Window", "Token Bucket", "Leaky Bucket", "Sliding Window"],
        correctIndex: 1,
        explanation: "Token Bucket adds tokens at a fixed rate; each request consumes a token, allowing smooth traffic flow.",
        difficulty: "medium",
      },
    ],
    architecture: {
      description: "Distributed rate limiting with Redis",
      nodes: [
        { id: "clients", label: "Clients", type: "user" },
        { id: "gw", label: "API Gateway", type: "gateway" },
        { id: "rl", label: "Rate Limiter", type: "service" },
        { id: "redis-cluster", label: "Redis Cluster", type: "cache" },
        { id: "backend", label: "Backend Services", type: "service" },
      ],
      edges: [
        { from: "clients", to: "gw", animated: true },
        { from: "gw", to: "rl" },
        { from: "rl", to: "redis-cluster" },
        { from: "gw", to: "backend", animated: true },
      ],
    },
  },
  {
    id: "cap-theorem",
    title: "CAP Theorem",
    subtitle: "The fundamental tradeoff in distributed systems",
    description: "CAP theorem states that a distributed data store can only provide two of three guarantees simultaneously: Consistency (every read returns the most recent write), Availability (every request receives a response), and Partition Tolerance (system continues despite network failures). In practice, partitions are inevitable, so you choose between CP and AP.",
    icon: "triangle",
    difficulty: "advanced",
    duration: "20 min",
    companies: ["Amazon (AP)", "Google Spanner (CP)", "Cassandra (AP)", "MongoDB (CP)"],
    prerequisites: ["Distributed systems basics", "Database concepts"],
    sections: [
      {
        id: "what-is",
        title: "The CAP Triangle",
        type: "visual",
        content: "CAP theorem is often visualized as a triangle. You can pick at most two vertices. In distributed systems, P (Partition Tolerance) is mandatory because network failures happen. So your choice is really between CP (Consistency + Partition) and AP (Availability + Partition).",
        visual: {
          description: "CAP theorem triangle",
          nodes: [
            { id: "c", label: "Consistency", type: "service" },
            { id: "a", label: "Availability", type: "service" },
            { id: "p", label: "Partition Tolerance", type: "service" },
            { id: "cp", label: "CP (Spanner, HBase)", type: "database" },
            { id: "ap", label: "AP (Cassandra, Dynamo)", type: "database" },
            { id: "ca", label: "CA (Single DB)", type: "database" },
          ],
          edges: [
            { from: "c", to: "a" },
            { from: "a", to: "p" },
            { from: "p", to: "c" },
            { from: "c", to: "cp" },
            { from: "p", to: "cp" },
            { from: "a", to: "ap" },
            { from: "p", to: "ap" },
            { from: "c", to: "ca" },
            { from: "a", to: "ca" },
          ],
        },
      },
      {
        id: "story",
        title: "The Phone Network",
        type: "story",
        content: "Two friends talking on a phone that cuts off. The CP approach: they wait (are unavailable) until the line reconnects to ensure every word arrives in order. The AP approach: they continue talking, accepting that some words might be lost (stale reads). You can't have both — either you stop to ensure consistency, or continue with potential inconsistency.",
        story: {
          context: "A phone call between two friends coordinating plans.",
          analogy: "CP = wait for perfect connection. AP = continue with gaps.",
          transition: "Now let's see how real systems make this tradeoff.",
        },
      },
      {
        id: "real-world",
        title: "Real-World Choices",
        type: "text",
        content: "CP Systems: Google Spanner, HBase, MongoDB (with write concern) — prioritize consistency, may reject writes during partition. AP Systems: Amazon DynamoDB, Cassandra, CouchDB — prioritize availability, accept eventual consistency. CA Systems: Traditional single-node databases — not distributed, so partitions don't apply.",
      },
    ],
    quiz: [
      {
        id: "cap-q1",
        question: "According to CAP theorem, how many guarantees can a distributed system provide simultaneously?",
        options: ["One", "Two", "Three", "None"],
        correctIndex: 1,
        explanation: "CAP theorem states a distributed system can only provide two of three guarantees: Consistency, Availability, and Partition Tolerance.",
        difficulty: "medium",
      },
      {
        id: "cap-q2",
        question: "Why do most distributed systems choose between CP and AP (not CA)?",
        options: ["CA is too slow", "Partitions are inevitable in networks", "CA systems can't scale", "Users prefer it"],
        correctIndex: 1,
        explanation: "Network partitions are inevitable in distributed systems, so Partition Tolerance is mandatory, leaving a choice between CP and AP.",
        difficulty: "hard",
      },
    ],
    architecture: {
      description: "CP vs AP system behavior during partition",
      nodes: [
        { id: "client", label: "Client Request", type: "user" },
        { id: "lb", label: "Load Balancer", type: "loadbalancer" },
        { id: "cp-system", label: "CP System", type: "database" },
        { id: "ap-system", label: "AP System", type: "database" },
        { id: "cp-node1", label: "Node (available)", type: "service" },
        { id: "cp-node2", label: "Node (partitioned)", type: "service" },
        { id: "ap-node1", label: "Node (available)", type: "service" },
        { id: "ap-node2", label: "Node (partitioned)", type: "service" },
      ],
      edges: [
        { from: "client", to: "lb" },
        { from: "lb", to: "cp-system", animated: true },
        { from: "lb", to: "ap-system", animated: true },
        { from: "cp-system", to: "cp-node1" },
        { from: "cp-system", to: "cp-node2", label: "× Partition" },
        { from: "ap-system", to: "ap-node1" },
        { from: "ap-system", to: "ap-node2", label: "× Partition" },
      ],
    },
  },
];

export const KNOWLEDGE_GRAPH: { nodes: KnowledgeNode[]; links: KnowledgeLink[] } = {
  nodes: [
    { id: "load-balancer", label: "Load Balancer", group: "infrastructure", description: "Distribute traffic across servers" },
    { id: "caching", label: "Caching", group: "performance", description: "Fast data retrieval layer" },
    { id: "databases", label: "SQL vs NoSQL", group: "data", description: "Database selection tradeoffs" },
    { id: "cdn", label: "CDN", group: "infrastructure", description: "Global content delivery" },
    { id: "message-queues", label: "Message Queues", group: "architecture", description: "Async service communication" },
    { id: "api-gateway", label: "API Gateway", group: "architecture", description: "Single entry point for services" },
    { id: "microservices", label: "Microservices", group: "architecture", description: "Independent deployable services" },
    { id: "consistent-hashing", label: "Consistent Hashing", group: "algorithms", description: "Efficient distributed data placement" },
    { id: "rate-limiting", label: "Rate Limiting", group: "security", description: "API traffic control" },
    { id: "cap-theorem", label: "CAP Theorem", group: "theory", description: "Distributed system tradeoffs" },
  ],
  links: [
    { source: "load-balancer", target: "caching", label: "improves" },
    { source: "load-balancer", target: "microservices", label: "routes to" },
    { source: "load-balancer", target: "api-gateway", label: "often paired" },
    { source: "caching", target: "cdn", label: "edge variant" },
    { source: "caching", target: "consistent-hashing", label: "uses" },
    { source: "databases", target: "cap-theorem", label: "governs" },
    { source: "databases", target: "consistent-hashing", label: "uses" },
    { source: "message-queues", target: "microservices", label: "decouples" },
    { source: "message-queues", target: "api-gateway", label: "backend for" },
    { source: "api-gateway", target: "microservices", label: "fronts" },
    { source: "api-gateway", target: "rate-limiting", label: "enforces" },
    { source: "microservices", target: "message-queues", label: "communicate via" },
    { source: "microservices", target: "caching", label: "needs" },
    { source: "consistent-hashing", target: "caching", label: "distributes" },
    { source: "cap-theorem", target: "databases", label: "applies to" },
    { source: "cdn", target: "load-balancer", label: "cooperates" },
    { source: "rate-limiting", target: "api-gateway", label: "runs on" },
  ],
};

export const DIFFICULTY_COLORS: Record<string, string> = {
  beginner: "text-green-500 bg-green-500/10 border-green-500/30",
  intermediate: "text-yellow-500 bg-yellow-500/10 border-yellow-500/30",
  advanced: "text-red-500 bg-red-500/10 border-red-500/30",
};

export function getTopic(id: string): Topic | undefined {
  return TOPICS.find((t) => t.id === id);
}
