/**
 * LEARNIFY AI — PORTFOLIO FACTORY 4.0
 * Design Presets: 15 Design Families, 10 Curated Palettes, 6 Typography Pairings
 */

import type {
  DesignFamilyId,
  DesignFamilyMeta,
  ColorPaletteId,
  ColorTokens,
  TypographyPairingId,
  TypographyTokens,
} from "./types";

export const DESIGN_FAMILIES: Record<DesignFamilyId, DesignFamilyMeta> = {
  "developer-dark": {
    id: "developer-dark",
    name: "Developer Dark",
    subtitle: "High-contrast IDE terminal aesthetic with cyan accents",
    description: "Deep obsidian surfaces, monospace accents, and developer-first information hierarchy.",
    category: "tech",
    defaultPalette: "midnight-developer",
    defaultTypography: "tech-mono",
    defaultHero: "developer-terminal",
    defaultProjectsLayout: "grid-bento",
    defaultSkillsLayout: "categorized-grid",
    defaultMotion: "subtle",
    tags: ["Developer", "Dark Mode", "Terminal", "Code"],
  },
  "modern-swiss": {
    id: "modern-swiss",
    name: "Modern Swiss",
    subtitle: "Clean asymmetric typography & crisp structural grid",
    description: "Inspired by international typographic style: disciplined whitespace and high readability.",
    category: "editorial",
    defaultPalette: "swiss-monochrome",
    defaultTypography: "clean-swiss",
    defaultHero: "centered-minimal",
    defaultProjectsLayout: "minimal-numbered",
    defaultSkillsLayout: "dock-pills",
    defaultMotion: "clean-fade",
    tags: ["Swiss", "Minimal", "Grid", "Editorial"],
  },
  "bento-grid": {
    id: "bento-grid",
    name: "Bento Grid",
    subtitle: "Framer-inspired modular cards with responsive masonry",
    description: "Organizes accomplishments, metrics, skills, and projects into dynamic bento cells.",
    category: "creative",
    defaultPalette: "nordic-slate",
    defaultTypography: "modern-sans",
    defaultHero: "bento-hero",
    defaultProjectsLayout: "grid-bento",
    defaultSkillsLayout: "bento-chips",
    defaultMotion: "smooth-spring",
    tags: ["Bento", "Framer", "Visual", "Modular"],
  },
  "premium-saas": {
    id: "premium-saas",
    name: "Premium SaaS",
    subtitle: "Linear & Vercel-grade polished developer product feel",
    description: "Refined borders, subtle ambient glow, and micro-interactions designed for tech leaders.",
    category: "corporate",
    defaultPalette: "learnify-brand",
    defaultTypography: "geometric-display",
    defaultHero: "split-profile",
    defaultProjectsLayout: "image-top-cards",
    defaultSkillsLayout: "categorized-grid",
    defaultMotion: "smooth-spring",
    tags: ["SaaS", "Linear", "Clean", "Corporate"],
  },
  "minimal-editorial": {
    id: "minimal-editorial",
    name: "Minimal Editorial",
    subtitle: "Serif typography with warm editorial magazine pacing",
    description: "Spacious layout with thoughtful typography pairings, ideal for thoughtful engineering writing.",
    category: "editorial",
    defaultPalette: "warm-editorial",
    defaultTypography: "editorial-serif",
    defaultHero: "editorial-headline",
    defaultProjectsLayout: "image-side-rows",
    defaultSkillsLayout: "minimal-cloud",
    defaultMotion: "clean-fade",
    tags: ["Editorial", "Serif", "Warm", "Thoughtful"],
  },
  "neo-brutalist": {
    id: "neo-brutalist",
    name: "Neo-Brutalist",
    subtitle: "Bold black borders, offset solid shadows, and high contrast",
    description: "Distinctive high-energy geometry with hard borders (2px) and playful solid drop-shadows.",
    category: "creative",
    defaultPalette: "minimal-light",
    defaultTypography: "modern-sans",
    defaultHero: "centered-minimal",
    defaultProjectsLayout: "image-top-cards",
    defaultSkillsLayout: "dock-pills",
    defaultMotion: "subtle",
    tags: ["Brutalist", "High-Contrast", "Playful", "Bold"],
  },
  "creative-portfolio": {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    subtitle: "Expressive project showcases with bold accent pops",
    description: "Vibrant visual hierarchy with large project cards and animated skill docks.",
    category: "creative",
    defaultPalette: "sunset-coral",
    defaultTypography: "geometric-display",
    defaultHero: "split-profile",
    defaultProjectsLayout: "featured-showcase",
    defaultSkillsLayout: "dock-pills",
    defaultMotion: "smooth-spring",
    tags: ["Creative", "Artistic", "Showcase", "Interactive"],
  },
  "academic-research": {
    id: "academic-research",
    name: "Academic & Research",
    subtitle: "Structured timeline, publications, and citation clarity",
    description: "Clear hierarchy for algorithms, papers, teaching, and research milestones.",
    category: "editorial",
    defaultPalette: "warm-editorial",
    defaultTypography: "editorial-serif",
    defaultHero: "editorial-headline",
    defaultProjectsLayout: "minimal-numbered",
    defaultSkillsLayout: "categorized-grid",
    defaultMotion: "none",
    tags: ["Research", "Academic", "Papers", "Formal"],
  },
  "product-designer": {
    id: "product-designer",
    name: "Product Designer",
    subtitle: "Case study galleries with design systems and impact metrics",
    description: "Full-width visual imagery, role breakdown, problem statements, and live prototype links.",
    category: "creative",
    defaultPalette: "tokyo-night",
    defaultTypography: "humanist",
    defaultHero: "split-profile",
    defaultProjectsLayout: "featured-showcase",
    defaultSkillsLayout: "bento-chips",
    defaultMotion: "smooth-spring",
    tags: ["UI/UX", "Design", "Case Study", "Figma"],
  },
  "ai-engineer": {
    id: "ai-engineer",
    name: "AI & ML Engineer",
    subtitle: "Neural network inspired obsidian with electric cyan accents",
    description: "Highlights models, datasets, LLM deployments, benchmark scores, and GitHub repos.",
    category: "tech",
    defaultPalette: "cyber-neon",
    defaultTypography: "tech-mono",
    defaultHero: "developer-terminal",
    defaultProjectsLayout: "grid-bento",
    defaultSkillsLayout: "categorized-grid",
    defaultMotion: "subtle",
    tags: ["AI", "Machine Learning", "LLM", "Deep Learning"],
  },
  "full-stack-dev": {
    id: "full-stack-dev",
    name: "Full-Stack Engineer",
    subtitle: "Architecture breakdown, tech stacks, and live application demos",
    description: "Highlights both backend system scalability and frontend UX finesse.",
    category: "tech",
    defaultPalette: "learnify-brand",
    defaultTypography: "modern-sans",
    defaultHero: "developer-terminal",
    defaultProjectsLayout: "image-top-cards",
    defaultSkillsLayout: "categorized-grid",
    defaultMotion: "subtle",
    tags: ["Full Stack", "React", "Node", "TypeScript"],
  },
  "student-fresher": {
    id: "student-fresher",
    name: "Student & Fresher",
    subtitle: "Projects, certifications, and high-growth potential front-and-center",
    description: "Focuses on passion projects, verified certifications, and core CS fundamentals.",
    category: "tech",
    defaultPalette: "emerald-growth",
    defaultTypography: "modern-sans",
    defaultHero: "centered-minimal",
    defaultProjectsLayout: "image-top-cards",
    defaultSkillsLayout: "dock-pills",
    defaultMotion: "subtle",
    tags: ["Student", "Intern", "Graduate", "Entry Level"],
  },
  "freelancer": {
    id: "freelancer",
    name: "Independent Consultant",
    subtitle: "Services offered, client testimonials, and 'Hire Me' call-to-actions",
    description: "Optimized for conversion: highlights client solutions, scope of services, and booking links.",
    category: "corporate",
    defaultPalette: "learnify-brand",
    defaultTypography: "geometric-display",
    defaultHero: "split-profile",
    defaultProjectsLayout: "featured-showcase",
    defaultSkillsLayout: "categorized-grid",
    defaultMotion: "smooth-spring",
    tags: ["Consultant", "Freelancer", "Services", "Hire"],
  },
  "creator": {
    id: "creator",
    name: "Content Creator & Educator",
    subtitle: "Media feeds, YouTube highlights, articles, and community proof",
    description: "Showcases media links, newsletters, community reach, and featured learning tutorials.",
    category: "creative",
    defaultPalette: "sunset-coral",
    defaultTypography: "humanist",
    defaultHero: "bento-hero",
    defaultProjectsLayout: "grid-bento",
    defaultSkillsLayout: "dock-pills",
    defaultMotion: "smooth-spring",
    tags: ["Creator", "YouTube", "Educator", "Media"],
  },
  "executive-pro": {
    id: "executive-pro",
    name: "Executive & Engineering Leader",
    subtitle: "Team scale, architectural leadership, and organizational impact",
    description: "Executive biography, advisory boards, high-scale engineering milestones, and speaking engagements.",
    category: "corporate",
    defaultPalette: "nordic-slate",
    defaultTypography: "clean-swiss",
    defaultHero: "split-profile",
    defaultProjectsLayout: "image-side-rows",
    defaultSkillsLayout: "categorized-grid",
    defaultMotion: "clean-fade",
    tags: ["Executive", "VP", "Director", "Leadership"],
  },
};

export const COLOR_PALETTES: Record<ColorPaletteId, ColorTokens> = {
  "learnify-brand": {
    background: "#0A1128",
    surface: "#101B3B",
    surfaceAlt: "#16234B",
    border: "#1E3066",
    text: "#F8FAFC",
    muted: "#94A3B8",
    primary: "#00A6FB",
    primaryHover: "#38BDF8",
    secondary: "#1D4ED8",
    accent: "#FB7185",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    contrastRatioText: 14.8,
  },
  "midnight-developer": {
    background: "#090D16",
    surface: "#111827",
    surfaceAlt: "#1F2937",
    border: "#374151",
    text: "#F9FAFB",
    muted: "#9CA3AF",
    primary: "#00D2FF",
    primaryHover: "#38BDF8",
    secondary: "#3B82F6",
    accent: "#A855F7",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    contrastRatioText: 15.2,
  },
  "swiss-monochrome": {
    background: "#FFFFFF",
    surface: "#F8FAFC",
    surfaceAlt: "#F1F5F9",
    border: "#E2E8F0",
    text: "#0F172A",
    muted: "#64748B",
    primary: "#0F172A",
    primaryHover: "#334155",
    secondary: "#475569",
    accent: "#2563EB",
    success: "#059669",
    warning: "#D97706",
    danger: "#DC2626",
    contrastRatioText: 16.5,
  },
  "warm-editorial": {
    background: "#FAF8F5",
    surface: "#F3EFEA",
    surfaceAlt: "#EBE5DE",
    border: "#D8CEBE",
    text: "#1C1917",
    muted: "#78716C",
    primary: "#C2410C",
    primaryHover: "#EA580C",
    secondary: "#44403C",
    accent: "#0284C7",
    success: "#16A34A",
    warning: "#D97706",
    danger: "#DC2626",
    contrastRatioText: 15.8,
  },
  "nordic-slate": {
    background: "#0F172A",
    surface: "#1E293B",
    surfaceAlt: "#334155",
    border: "#475569",
    text: "#F8FAFC",
    muted: "#94A3B8",
    primary: "#38BDF8",
    primaryHover: "#7DD3FC",
    secondary: "#64748B",
    accent: "#818CF8",
    success: "#34D399",
    warning: "#FBBF24",
    danger: "#F87171",
    contrastRatioText: 13.9,
  },
  "cyber-neon": {
    background: "#050508",
    surface: "#0D0E18",
    surfaceAlt: "#171829",
    border: "#252742",
    text: "#FAFAFA",
    muted: "#8A8FA3",
    primary: "#10B981",
    primaryHover: "#34D399",
    secondary: "#06B6D4",
    accent: "#8B5CF6",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    contrastRatioText: 16.8,
  },
  "minimal-light": {
    background: "#F9FAFB",
    surface: "#FFFFFF",
    surfaceAlt: "#F3F4F6",
    border: "#E5E7EB",
    text: "#111827",
    muted: "#6B7280",
    primary: "#4F46E5",
    primaryHover: "#4338CA",
    secondary: "#374151",
    accent: "#EC4899",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    contrastRatioText: 15.6,
  },
  "tokyo-night": {
    background: "#1A1B26",
    surface: "#24283B",
    surfaceAlt: "#2F354F",
    border: "#414868",
    text: "#C0CAF5",
    muted: "#7AA2F7",
    primary: "#BB9AF7",
    primaryHover: "#C678DD",
    secondary: "#7AA2F7",
    accent: "#7DCFFF",
    success: "#9ECE6A",
    warning: "#E0AF68",
    danger: "#F7768E",
    contrastRatioText: 9.8,
  },
  "emerald-growth": {
    background: "#061A14",
    surface: "#0D2E24",
    surfaceAlt: "#144234",
    border: "#1E5E4A",
    text: "#ECFDF5",
    muted: "#6EE7B7",
    primary: "#10B981",
    primaryHover: "#34D399",
    secondary: "#059669",
    accent: "#F59E0B",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    contrastRatioText: 14.5,
  },
  "sunset-coral": {
    background: "#181113",
    surface: "#29191D",
    surfaceAlt: "#3B2228",
    border: "#522E37",
    text: "#FFF1F2",
    muted: "#FDA4AF",
    primary: "#F43F5E",
    primaryHover: "#FB7185",
    secondary: "#E11D48",
    accent: "#F59E0B",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    contrastRatioText: 13.8,
  },
};

export const TYPOGRAPHY_PAIRINGS: Record<TypographyPairingId, TypographyTokens> = {
  "modern-sans": {
    displayFont: "Space Grotesk",
    bodyFont: "DM Sans",
    codeFont: "JetBrains Mono",
    displayFontFamily: "'Space Grotesk', system-ui, -apple-system, sans-serif",
    bodyFontFamily: "'DM Sans', system-ui, -apple-system, sans-serif",
    codeFontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
  "editorial-serif": {
    displayFont: "Playfair Display",
    bodyFont: "Inter",
    codeFont: "Space Mono",
    displayFontFamily: "'Playfair Display', Georgia, serif",
    bodyFontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    codeFontFamily: "'Space Mono', ui-monospace, monospace",
  },
  "tech-mono": {
    displayFont: "JetBrains Mono",
    bodyFont: "DM Sans",
    codeFont: "JetBrains Mono",
    displayFontFamily: "'JetBrains Mono', ui-monospace, monospace",
    bodyFontFamily: "'DM Sans', system-ui, -apple-system, sans-serif",
    codeFontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
  "clean-swiss": {
    displayFont: "Inter",
    bodyFont: "Inter",
    codeFont: "Courier New",
    displayFontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    bodyFontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    codeFontFamily: "'Courier New', Courier, monospace",
  },
  "geometric-display": {
    displayFont: "Outfit",
    bodyFont: "Plus Jakarta Sans",
    codeFont: "JetBrains Mono",
    displayFontFamily: "'Outfit', system-ui, sans-serif",
    bodyFontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    codeFontFamily: "'JetBrains Mono', monospace",
  },
  "humanist": {
    displayFont: "Sora",
    bodyFont: "DM Sans",
    codeFont: "Space Mono",
    displayFontFamily: "'Sora', system-ui, sans-serif",
    bodyFontFamily: "'DM Sans', system-ui, sans-serif",
    codeFontFamily: "'Space Mono', monospace",
  },
};
