/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as CertificatesCodeRouteImport } from './routes/certificates.$code'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreatorRouteImport } from './routes/_authenticated/creator'
import { Route as AuthenticatedCommunityFeedRouteImport } from './routes/_authenticated/community-feed'
import { Route as AuthenticatedCohortsRouteImport } from './routes/_authenticated/cohorts'
import { Route as AuthenticatedCoachingRouteImport } from './routes/_authenticated/coaching'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedApplyCreatorRouteImport } from './routes/_authenticated/apply-creator'
import { Route as AuthenticatedAiToolsRouteImport } from './routes/_authenticated/ai-tools'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedCreatorsIdRouteImport } from './routes/_authenticated/creators.$id'
import { Route as AuthenticatedCreatorSubscribersRouteImport } from './routes/_authenticated/creator.subscribers'
import { Route as AuthenticatedCreatorSettingsRouteImport } from './routes/_authenticated/creator.settings'
import { Route as AuthenticatedCreatorEarningsRouteImport } from './routes/_authenticated/creator.earnings'
import { Route as AuthenticatedCreatorCommentsRouteImport } from './routes/_authenticated/creator.comments'
import { Route as AuthenticatedCoursesSlugRouteImport } from './routes/_authenticated/courses.$slug'
import { Route as AuthenticatedCohortsIdRouteImport } from './routes/_authenticated/cohorts.$id'
import { Route as AuthenticatedAdminMissingVideosRouteImport } from './routes/_authenticated/admin.missing-videos'
import { Route as AuthenticatedAdminEnrichmentRunsRouteImport } from './routes/_authenticated/admin.enrichment-runs'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as ApiPublicHooksRunRemindersRouteImport } from './routes/api/public/hooks/run-reminders'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCodeRoute = CertificatesCodeRouteImport.update({
  id: '/certificates/$code',
  path: '/certificates/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreatorRoute = AuthenticatedCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityFeedRoute =
  AuthenticatedCommunityFeedRouteImport.update({
    id: '/community-feed',
    path: '/community-feed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsRoute = AuthenticatedCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachingRoute = AuthenticatedCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplyCreatorRoute =
  AuthenticatedApplyCreatorRouteImport.update({
    id: '/apply-creator',
    path: '/apply-creator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiToolsRoute = AuthenticatedAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreatorsIdRoute = AuthenticatedCreatorsIdRouteImport.update({
  id: '/creators/$id',
  path: '/creators/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreatorSubscribersRoute =
  AuthenticatedCreatorSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedCreatorRoute,
  } as any)
const AuthenticatedCreatorSettingsRoute =
  AuthenticatedCreatorSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCreatorRoute,
  } as any)
const AuthenticatedCreatorEarningsRoute =
  AuthenticatedCreatorEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedCreatorRoute,
  } as any)
const AuthenticatedCreatorCommentsRoute =
  AuthenticatedCreatorCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedCreatorRoute,
  } as any)
const AuthenticatedCoursesSlugRoute =
  AuthenticatedCoursesSlugRouteImport.update({
    id: '/courses/$slug',
    path: '/courses/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsIdRoute = AuthenticatedCohortsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCohortsRoute,
} as any)
const AuthenticatedAdminMissingVideosRoute =
  AuthenticatedAdminMissingVideosRouteImport.update({
    id: '/missing-videos',
    path: '/missing-videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnrichmentRunsRoute =
  AuthenticatedAdminEnrichmentRunsRouteImport.update({
    id: '/enrichment-runs',
    path: '/enrichment-runs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksRunRemindersRoute =
  ApiPublicHooksRunRemindersRouteImport.update({
    id: '/api/public/hooks/run-reminders',
    path: '/api/public/hooks/run-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/apply-creator': typeof AuthenticatedApplyCreatorRoute
  '/cart': typeof AuthenticatedCartRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/coaching': typeof AuthenticatedCoachingRoute
  '/cohorts': typeof AuthenticatedCohortsRouteWithChildren
  '/community-feed': typeof AuthenticatedCommunityFeedRoute
  '/creator': typeof AuthenticatedCreatorRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/chat': typeof ApiChatRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/u/$id': typeof UIdRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/enrichment-runs': typeof AuthenticatedAdminEnrichmentRunsRoute
  '/admin/missing-videos': typeof AuthenticatedAdminMissingVideosRoute
  '/cohorts/$id': typeof AuthenticatedCohortsIdRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/creator/comments': typeof AuthenticatedCreatorCommentsRoute
  '/creator/earnings': typeof AuthenticatedCreatorEarningsRoute
  '/creator/settings': typeof AuthenticatedCreatorSettingsRoute
  '/creator/subscribers': typeof AuthenticatedCreatorSubscribersRoute
  '/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/apply-creator': typeof AuthenticatedApplyCreatorRoute
  '/cart': typeof AuthenticatedCartRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/coaching': typeof AuthenticatedCoachingRoute
  '/cohorts': typeof AuthenticatedCohortsRouteWithChildren
  '/community-feed': typeof AuthenticatedCommunityFeedRoute
  '/creator': typeof AuthenticatedCreatorRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/chat': typeof ApiChatRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/u/$id': typeof UIdRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/enrichment-runs': typeof AuthenticatedAdminEnrichmentRunsRoute
  '/admin/missing-videos': typeof AuthenticatedAdminMissingVideosRoute
  '/cohorts/$id': typeof AuthenticatedCohortsIdRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/creator/comments': typeof AuthenticatedCreatorCommentsRoute
  '/creator/earnings': typeof AuthenticatedCreatorEarningsRoute
  '/creator/settings': typeof AuthenticatedCreatorSettingsRoute
  '/creator/subscribers': typeof AuthenticatedCreatorSubscribersRoute
  '/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/ai-tools': typeof AuthenticatedAiToolsRoute
  '/_authenticated/apply-creator': typeof AuthenticatedApplyCreatorRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/coaching': typeof AuthenticatedCoachingRoute
  '/_authenticated/cohorts': typeof AuthenticatedCohortsRouteWithChildren
  '/_authenticated/community-feed': typeof AuthenticatedCommunityFeedRoute
  '/_authenticated/creator': typeof AuthenticatedCreatorRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/chat': typeof ApiChatRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/u/$id': typeof UIdRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/enrichment-runs': typeof AuthenticatedAdminEnrichmentRunsRoute
  '/_authenticated/admin/missing-videos': typeof AuthenticatedAdminMissingVideosRoute
  '/_authenticated/cohorts/$id': typeof AuthenticatedCohortsIdRoute
  '/_authenticated/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/_authenticated/creator/comments': typeof AuthenticatedCreatorCommentsRoute
  '/_authenticated/creator/earnings': typeof AuthenticatedCreatorEarningsRoute
  '/_authenticated/creator/settings': typeof AuthenticatedCreatorSettingsRoute
  '/_authenticated/creator/subscribers': typeof AuthenticatedCreatorSubscribersRoute
  '/_authenticated/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/creators'
    | '/events'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/roadmap'
    | '/signup'
    | '/admin'
    | '/ai'
    | '/ai-tools'
    | '/apply-creator'
    | '/cart'
    | '/certificates'
    | '/coaching'
    | '/cohorts'
    | '/community-feed'
    | '/creator'
    | '/dashboard'
    | '/inbox'
    | '/leaderboard'
    | '/settings'
    | '/studio'
    | '/submissions'
    | '/wallet'
    | '/api/chat'
    | '/certificates/$code'
    | '/u/$id'
    | '/admin/content'
    | '/admin/enrichment-runs'
    | '/admin/missing-videos'
    | '/cohorts/$id'
    | '/courses/$slug'
    | '/creator/comments'
    | '/creator/earnings'
    | '/creator/settings'
    | '/creator/subscribers'
    | '/creators/$id'
    | '/courses/'
    | '/api/public/hooks/run-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/creators'
    | '/events'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/roadmap'
    | '/signup'
    | '/admin'
    | '/ai'
    | '/ai-tools'
    | '/apply-creator'
    | '/cart'
    | '/certificates'
    | '/coaching'
    | '/cohorts'
    | '/community-feed'
    | '/creator'
    | '/dashboard'
    | '/inbox'
    | '/leaderboard'
    | '/settings'
    | '/studio'
    | '/submissions'
    | '/wallet'
    | '/api/chat'
    | '/certificates/$code'
    | '/u/$id'
    | '/admin/content'
    | '/admin/enrichment-runs'
    | '/admin/missing-videos'
    | '/cohorts/$id'
    | '/courses/$slug'
    | '/creator/comments'
    | '/creator/earnings'
    | '/creator/settings'
    | '/creator/subscribers'
    | '/creators/$id'
    | '/courses'
    | '/api/public/hooks/run-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/creators'
    | '/events'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/roadmap'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/ai-tools'
    | '/_authenticated/apply-creator'
    | '/_authenticated/cart'
    | '/_authenticated/certificates'
    | '/_authenticated/coaching'
    | '/_authenticated/cohorts'
    | '/_authenticated/community-feed'
    | '/_authenticated/creator'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/leaderboard'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/submissions'
    | '/_authenticated/wallet'
    | '/api/chat'
    | '/certificates/$code'
    | '/u/$id'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/enrichment-runs'
    | '/_authenticated/admin/missing-videos'
    | '/_authenticated/cohorts/$id'
    | '/_authenticated/courses/$slug'
    | '/_authenticated/creator/comments'
    | '/_authenticated/creator/earnings'
    | '/_authenticated/creator/settings'
    | '/_authenticated/creator/subscribers'
    | '/_authenticated/creators/$id'
    | '/_authenticated/courses/'
    | '/api/public/hooks/run-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CoachesRoute: typeof CoachesRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CreatorsRoute: typeof CreatorsRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  CertificatesCodeRoute: typeof CertificatesCodeRoute
  UIdRoute: typeof UIdRoute
  ApiPublicHooksRunRemindersRoute: typeof ApiPublicHooksRunRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$code': {
      id: '/certificates/$code'
      path: '/certificates/$code'
      fullPath: '/certificates/$code'
      preLoaderRoute: typeof CertificatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creator': {
      id: '/_authenticated/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AuthenticatedCreatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community-feed': {
      id: '/_authenticated/community-feed'
      path: '/community-feed'
      fullPath: '/community-feed'
      preLoaderRoute: typeof AuthenticatedCommunityFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts': {
      id: '/_authenticated/cohorts'
      path: '/cohorts'
      fullPath: '/cohorts'
      preLoaderRoute: typeof AuthenticatedCohortsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coaching': {
      id: '/_authenticated/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof AuthenticatedCoachingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apply-creator': {
      id: '/_authenticated/apply-creator'
      path: '/apply-creator'
      fullPath: '/apply-creator'
      preLoaderRoute: typeof AuthenticatedApplyCreatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools': {
      id: '/_authenticated/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AuthenticatedAiToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creators/$id': {
      id: '/_authenticated/creators/$id'
      path: '/creators/$id'
      fullPath: '/creators/$id'
      preLoaderRoute: typeof AuthenticatedCreatorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creator/subscribers': {
      id: '/_authenticated/creator/subscribers'
      path: '/subscribers'
      fullPath: '/creator/subscribers'
      preLoaderRoute: typeof AuthenticatedCreatorSubscribersRouteImport
      parentRoute: typeof AuthenticatedCreatorRoute
    }
    '/_authenticated/creator/settings': {
      id: '/_authenticated/creator/settings'
      path: '/settings'
      fullPath: '/creator/settings'
      preLoaderRoute: typeof AuthenticatedCreatorSettingsRouteImport
      parentRoute: typeof AuthenticatedCreatorRoute
    }
    '/_authenticated/creator/earnings': {
      id: '/_authenticated/creator/earnings'
      path: '/earnings'
      fullPath: '/creator/earnings'
      preLoaderRoute: typeof AuthenticatedCreatorEarningsRouteImport
      parentRoute: typeof AuthenticatedCreatorRoute
    }
    '/_authenticated/creator/comments': {
      id: '/_authenticated/creator/comments'
      path: '/comments'
      fullPath: '/creator/comments'
      preLoaderRoute: typeof AuthenticatedCreatorCommentsRouteImport
      parentRoute: typeof AuthenticatedCreatorRoute
    }
    '/_authenticated/courses/$slug': {
      id: '/_authenticated/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AuthenticatedCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/$id': {
      id: '/_authenticated/cohorts/$id'
      path: '/$id'
      fullPath: '/cohorts/$id'
      preLoaderRoute: typeof AuthenticatedCohortsIdRouteImport
      parentRoute: typeof AuthenticatedCohortsRoute
    }
    '/_authenticated/admin/missing-videos': {
      id: '/_authenticated/admin/missing-videos'
      path: '/missing-videos'
      fullPath: '/admin/missing-videos'
      preLoaderRoute: typeof AuthenticatedAdminMissingVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enrichment-runs': {
      id: '/_authenticated/admin/enrichment-runs'
      path: '/enrichment-runs'
      fullPath: '/admin/enrichment-runs'
      preLoaderRoute: typeof AuthenticatedAdminEnrichmentRunsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/run-reminders': {
      id: '/api/public/hooks/run-reminders'
      path: '/api/public/hooks/run-reminders'
      fullPath: '/api/public/hooks/run-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminEnrichmentRunsRoute: typeof AuthenticatedAdminEnrichmentRunsRoute
  AuthenticatedAdminMissingVideosRoute: typeof AuthenticatedAdminMissingVideosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminEnrichmentRunsRoute: AuthenticatedAdminEnrichmentRunsRoute,
  AuthenticatedAdminMissingVideosRoute: AuthenticatedAdminMissingVideosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCohortsRouteChildren {
  AuthenticatedCohortsIdRoute: typeof AuthenticatedCohortsIdRoute
}

const AuthenticatedCohortsRouteChildren: AuthenticatedCohortsRouteChildren = {
  AuthenticatedCohortsIdRoute: AuthenticatedCohortsIdRoute,
}

const AuthenticatedCohortsRouteWithChildren =
  AuthenticatedCohortsRoute._addFileChildren(AuthenticatedCohortsRouteChildren)

interface AuthenticatedCreatorRouteChildren {
  AuthenticatedCreatorCommentsRoute: typeof AuthenticatedCreatorCommentsRoute
  AuthenticatedCreatorEarningsRoute: typeof AuthenticatedCreatorEarningsRoute
  AuthenticatedCreatorSettingsRoute: typeof AuthenticatedCreatorSettingsRoute
  AuthenticatedCreatorSubscribersRoute: typeof AuthenticatedCreatorSubscribersRoute
}

const AuthenticatedCreatorRouteChildren: AuthenticatedCreatorRouteChildren = {
  AuthenticatedCreatorCommentsRoute: AuthenticatedCreatorCommentsRoute,
  AuthenticatedCreatorEarningsRoute: AuthenticatedCreatorEarningsRoute,
  AuthenticatedCreatorSettingsRoute: AuthenticatedCreatorSettingsRoute,
  AuthenticatedCreatorSubscribersRoute: AuthenticatedCreatorSubscribersRoute,
}

const AuthenticatedCreatorRouteWithChildren =
  AuthenticatedCreatorRoute._addFileChildren(AuthenticatedCreatorRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAiToolsRoute: typeof AuthenticatedAiToolsRoute
  AuthenticatedApplyCreatorRoute: typeof AuthenticatedApplyCreatorRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedCoachingRoute: typeof AuthenticatedCoachingRoute
  AuthenticatedCohortsRoute: typeof AuthenticatedCohortsRouteWithChildren
  AuthenticatedCommunityFeedRoute: typeof AuthenticatedCommunityFeedRoute
  AuthenticatedCreatorRoute: typeof AuthenticatedCreatorRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedCoursesSlugRoute: typeof AuthenticatedCoursesSlugRoute
  AuthenticatedCreatorsIdRoute: typeof AuthenticatedCreatorsIdRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAiToolsRoute: AuthenticatedAiToolsRoute,
  AuthenticatedApplyCreatorRoute: AuthenticatedApplyCreatorRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedCoachingRoute: AuthenticatedCoachingRoute,
  AuthenticatedCohortsRoute: AuthenticatedCohortsRouteWithChildren,
  AuthenticatedCommunityFeedRoute: AuthenticatedCommunityFeedRoute,
  AuthenticatedCreatorRoute: AuthenticatedCreatorRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedCoursesSlugRoute: AuthenticatedCoursesSlugRoute,
  AuthenticatedCreatorsIdRoute: AuthenticatedCreatorsIdRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CoachesRoute: CoachesRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CreatorsRoute: CreatorsRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  CertificatesCodeRoute: CertificatesCodeRoute,
  UIdRoute: UIdRoute,
  ApiPublicHooksRunRemindersRoute: ApiPublicHooksRunRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
