/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as UAtusernameRouteImport } from './routes/u/@$username'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as CertificatesCodeRouteImport } from './routes/certificates.$code'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlaygroundRouteImport } from './routes/_authenticated/playground'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreatorRouteImport } from './routes/_authenticated/creator'
import { Route as AuthenticatedCommunityFeedRouteImport } from './routes/_authenticated/community-feed'
import { Route as AuthenticatedCohortsRouteImport } from './routes/_authenticated/cohorts'
import { Route as AuthenticatedCoachingRouteImport } from './routes/_authenticated/coaching'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApplyCreatorRouteImport } from './routes/_authenticated/apply-creator'
import { Route as AuthenticatedAiToolsRouteImport } from './routes/_authenticated/ai-tools'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as ApiWebhooksCashfreeSubscriptionRouteImport } from './routes/api/webhooks/cashfree-subscription'
import { Route as ApiWebhooksCashfreeRouteImport } from './routes/api/webhooks/cashfree'
import { Route as AuthenticatedPlaygroundWebRouteImport } from './routes/_authenticated/playground.web'
import { Route as AuthenticatedPlaygroundReactRouteImport } from './routes/_authenticated/playground.react'
import { Route as AuthenticatedPlaygroundProjectsRouteImport } from './routes/_authenticated/playground.projects'
import { Route as AuthenticatedPlaygroundLeaderboardRouteImport } from './routes/_authenticated/playground.leaderboard'
import { Route as AuthenticatedPlaygroundInterviewRouteImport } from './routes/_authenticated/playground.interview'
import { Route as AuthenticatedPlaygroundEditorRouteImport } from './routes/_authenticated/playground.editor'
import { Route as AuthenticatedPlaygroundChallengesRouteImport } from './routes/_authenticated/playground.challenges'
import { Route as AuthenticatedCreatorsIdRouteImport } from './routes/_authenticated/creators.$id'
import { Route as AuthenticatedCreatorSubscribersRouteImport } from './routes/_authenticated/creator.subscribers'
import { Route as AuthenticatedCreatorEarningsRouteImport } from './routes/_authenticated/creator.earnings'
import { Route as AuthenticatedCreatorCommentsRouteImport } from './routes/_authenticated/creator.comments'
import { Route as AuthenticatedCoursesSlugRouteImport } from './routes/_authenticated/courses.$slug'
import { Route as AuthenticatedCohortsIdRouteImport } from './routes/_authenticated/cohorts.$id'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin/subscriptions'
import { Route as AuthenticatedAdminMissingVideosRouteImport } from './routes/_authenticated/admin.missing-videos'
import { Route as AuthenticatedAdminEnrichmentRunsRouteImport } from './routes/_authenticated/admin.enrichment-runs'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as ApiPublicHooksRunRemindersRouteImport } from './routes/api/public/hooks/run-reminders'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UAtusernameRoute = UAtusernameRouteImport.update({
  id: '/u/@$username',
  path: '/u/@$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCodeRoute = CertificatesCodeRouteImport.update({
  id: '/certificates/$code',
  path: '/certificates/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlaygroundRoute = AuthenticatedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreatorRoute = AuthenticatedCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityFeedRoute =
  AuthenticatedCommunityFeedRouteImport.update({
    id: '/community-feed',
    path: '/community-feed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsRoute = AuthenticatedCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachingRoute = AuthenticatedCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplyCreatorRoute =
  AuthenticatedApplyCreatorRouteImport.update({
    id: '/apply-creator',
    path: '/apply-creator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiToolsRoute = AuthenticatedAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiWebhooksCashfreeSubscriptionRoute =
  ApiWebhooksCashfreeSubscriptionRouteImport.update({
    id: '/api/webhooks/cashfree-subscription',
    path: '/api/webhooks/cashfree-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksCashfreeRoute = ApiWebhooksCashfreeRouteImport.update({
  id: '/api/webhooks/cashfree',
  path: '/api/webhooks/cashfree',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaygroundWebRoute =
  AuthenticatedPlaygroundWebRouteImport.update({
    id: '/web',
    path: '/web',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundReactRoute =
  AuthenticatedPlaygroundReactRouteImport.update({
    id: '/react',
    path: '/react',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundProjectsRoute =
  AuthenticatedPlaygroundProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundLeaderboardRoute =
  AuthenticatedPlaygroundLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundInterviewRoute =
  AuthenticatedPlaygroundInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundEditorRoute =
  AuthenticatedPlaygroundEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundChallengesRoute =
  AuthenticatedPlaygroundChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedCreatorsIdRoute = AuthenticatedCreatorsIdRouteImport.update({
  id: '/creators/$id',
  path: '/creators/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreatorSubscribersRoute =
  AuthenticatedCreatorSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedCreatorRoute,
  } as any)
const AuthenticatedCreatorEarningsRoute =
  AuthenticatedCreatorEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedCreatorRoute,
  } as any)
const AuthenticatedCreatorCommentsRoute =
  AuthenticatedCreatorCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedCreatorRoute,
  } as any)
const AuthenticatedCoursesSlugRoute =
  AuthenticatedCoursesSlugRouteImport.update({
    id: '/courses/$slug',
    path: '/courses/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsIdRoute = AuthenticatedCohortsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCohortsRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMissingVideosRoute =
  AuthenticatedAdminMissingVideosRouteImport.update({
    id: '/missing-videos',
    path: '/missing-videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnrichmentRunsRoute =
  AuthenticatedAdminEnrichmentRunsRouteImport.update({
    id: '/enrichment-runs',
    path: '/enrichment-runs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksRunRemindersRoute =
  ApiPublicHooksRunRemindersRouteImport.update({
    id: '/api/public/hooks/run-reminders',
    path: '/api/public/hooks/run-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/apply-creator': typeof AuthenticatedApplyCreatorRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cart': typeof AuthenticatedCartRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/coaching': typeof AuthenticatedCoachingRoute
  '/cohorts': typeof AuthenticatedCohortsRouteWithChildren
  '/community-feed': typeof AuthenticatedCommunityFeedRoute
  '/creator': typeof AuthenticatedCreatorRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/playground': typeof AuthenticatedPlaygroundRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/u/$id': typeof UIdRoute
  '/u/@$username': typeof UAtusernameRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/enrichment-runs': typeof AuthenticatedAdminEnrichmentRunsRoute
  '/admin/missing-videos': typeof AuthenticatedAdminMissingVideosRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/cohorts/$id': typeof AuthenticatedCohortsIdRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/creator/comments': typeof AuthenticatedCreatorCommentsRoute
  '/creator/earnings': typeof AuthenticatedCreatorEarningsRoute
  '/creator/subscribers': typeof AuthenticatedCreatorSubscribersRoute
  '/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/playground/challenges': typeof AuthenticatedPlaygroundChallengesRoute
  '/playground/editor': typeof AuthenticatedPlaygroundEditorRoute
  '/playground/interview': typeof AuthenticatedPlaygroundInterviewRoute
  '/playground/leaderboard': typeof AuthenticatedPlaygroundLeaderboardRoute
  '/playground/projects': typeof AuthenticatedPlaygroundProjectsRoute
  '/playground/react': typeof AuthenticatedPlaygroundReactRoute
  '/playground/web': typeof AuthenticatedPlaygroundWebRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
  '/api/webhooks/cashfree-subscription': typeof ApiWebhooksCashfreeSubscriptionRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/apply-creator': typeof AuthenticatedApplyCreatorRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cart': typeof AuthenticatedCartRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/coaching': typeof AuthenticatedCoachingRoute
  '/cohorts': typeof AuthenticatedCohortsRouteWithChildren
  '/community-feed': typeof AuthenticatedCommunityFeedRoute
  '/creator': typeof AuthenticatedCreatorRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/playground': typeof AuthenticatedPlaygroundRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/u/$id': typeof UIdRoute
  '/u/@$username': typeof UAtusernameRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/enrichment-runs': typeof AuthenticatedAdminEnrichmentRunsRoute
  '/admin/missing-videos': typeof AuthenticatedAdminMissingVideosRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/cohorts/$id': typeof AuthenticatedCohortsIdRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/creator/comments': typeof AuthenticatedCreatorCommentsRoute
  '/creator/earnings': typeof AuthenticatedCreatorEarningsRoute
  '/creator/subscribers': typeof AuthenticatedCreatorSubscribersRoute
  '/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/playground/challenges': typeof AuthenticatedPlaygroundChallengesRoute
  '/playground/editor': typeof AuthenticatedPlaygroundEditorRoute
  '/playground/interview': typeof AuthenticatedPlaygroundInterviewRoute
  '/playground/leaderboard': typeof AuthenticatedPlaygroundLeaderboardRoute
  '/playground/projects': typeof AuthenticatedPlaygroundProjectsRoute
  '/playground/react': typeof AuthenticatedPlaygroundReactRoute
  '/playground/web': typeof AuthenticatedPlaygroundWebRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
  '/api/webhooks/cashfree-subscription': typeof ApiWebhooksCashfreeSubscriptionRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/ai-tools': typeof AuthenticatedAiToolsRoute
  '/_authenticated/apply-creator': typeof AuthenticatedApplyCreatorRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/coaching': typeof AuthenticatedCoachingRoute
  '/_authenticated/cohorts': typeof AuthenticatedCohortsRouteWithChildren
  '/_authenticated/community-feed': typeof AuthenticatedCommunityFeedRoute
  '/_authenticated/creator': typeof AuthenticatedCreatorRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/u/$id': typeof UIdRoute
  '/u/@$username': typeof UAtusernameRoute
  '/verify/$id': typeof VerifyIdRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/enrichment-runs': typeof AuthenticatedAdminEnrichmentRunsRoute
  '/_authenticated/admin/missing-videos': typeof AuthenticatedAdminMissingVideosRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/cohorts/$id': typeof AuthenticatedCohortsIdRoute
  '/_authenticated/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/_authenticated/creator/comments': typeof AuthenticatedCreatorCommentsRoute
  '/_authenticated/creator/earnings': typeof AuthenticatedCreatorEarningsRoute
  '/_authenticated/creator/subscribers': typeof AuthenticatedCreatorSubscribersRoute
  '/_authenticated/creators/$id': typeof AuthenticatedCreatorsIdRoute
  '/_authenticated/playground/challenges': typeof AuthenticatedPlaygroundChallengesRoute
  '/_authenticated/playground/editor': typeof AuthenticatedPlaygroundEditorRoute
  '/_authenticated/playground/interview': typeof AuthenticatedPlaygroundInterviewRoute
  '/_authenticated/playground/leaderboard': typeof AuthenticatedPlaygroundLeaderboardRoute
  '/_authenticated/playground/projects': typeof AuthenticatedPlaygroundProjectsRoute
  '/_authenticated/playground/react': typeof AuthenticatedPlaygroundReactRoute
  '/_authenticated/playground/web': typeof AuthenticatedPlaygroundWebRoute
  '/api/webhooks/cashfree': typeof ApiWebhooksCashfreeRoute
  '/api/webhooks/cashfree-subscription': typeof ApiWebhooksCashfreeSubscriptionRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/creators'
    | '/events'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/roadmap'
    | '/showcase'
    | '/signup'
    | '/terms'
    | '/achievements'
    | '/admin'
    | '/ai'
    | '/ai-tools'
    | '/apply-creator'
    | '/billing'
    | '/cart'
    | '/certificates'
    | '/coaching'
    | '/cohorts'
    | '/community-feed'
    | '/creator'
    | '/dashboard'
    | '/inbox'
    | '/leaderboard'
    | '/playground'
    | '/settings'
    | '/studio'
    | '/submissions'
    | '/support'
    | '/wallet'
    | '/workspace'
    | '/api/chat'
    | '/certificates/$code'
    | '/sitemap/xml'
    | '/u/$id'
    | '/u/@$username'
    | '/verify/$id'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/enrichment-runs'
    | '/admin/missing-videos'
    | '/admin/subscriptions'
    | '/cohorts/$id'
    | '/courses/$slug'
    | '/creator/comments'
    | '/creator/earnings'
    | '/creator/subscribers'
    | '/creators/$id'
    | '/playground/challenges'
    | '/playground/editor'
    | '/playground/interview'
    | '/playground/leaderboard'
    | '/playground/projects'
    | '/playground/react'
    | '/playground/web'
    | '/api/webhooks/cashfree'
    | '/api/webhooks/cashfree-subscription'
    | '/courses/'
    | '/api/public/hooks/run-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/creators'
    | '/events'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/roadmap'
    | '/showcase'
    | '/signup'
    | '/terms'
    | '/achievements'
    | '/admin'
    | '/ai'
    | '/ai-tools'
    | '/apply-creator'
    | '/billing'
    | '/cart'
    | '/certificates'
    | '/coaching'
    | '/cohorts'
    | '/community-feed'
    | '/creator'
    | '/dashboard'
    | '/inbox'
    | '/leaderboard'
    | '/playground'
    | '/settings'
    | '/studio'
    | '/submissions'
    | '/support'
    | '/wallet'
    | '/workspace'
    | '/api/chat'
    | '/certificates/$code'
    | '/sitemap/xml'
    | '/u/$id'
    | '/u/@$username'
    | '/verify/$id'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/enrichment-runs'
    | '/admin/missing-videos'
    | '/admin/subscriptions'
    | '/cohorts/$id'
    | '/courses/$slug'
    | '/creator/comments'
    | '/creator/earnings'
    | '/creator/subscribers'
    | '/creators/$id'
    | '/playground/challenges'
    | '/playground/editor'
    | '/playground/interview'
    | '/playground/leaderboard'
    | '/playground/projects'
    | '/playground/react'
    | '/playground/web'
    | '/api/webhooks/cashfree'
    | '/api/webhooks/cashfree-subscription'
    | '/courses'
    | '/api/public/hooks/run-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/careers'
    | '/coaches'
    | '/community'
    | '/contact'
    | '/creators'
    | '/events'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/roadmap'
    | '/showcase'
    | '/signup'
    | '/terms'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/ai-tools'
    | '/_authenticated/apply-creator'
    | '/_authenticated/billing'
    | '/_authenticated/cart'
    | '/_authenticated/certificates'
    | '/_authenticated/coaching'
    | '/_authenticated/cohorts'
    | '/_authenticated/community-feed'
    | '/_authenticated/creator'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/leaderboard'
    | '/_authenticated/playground'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/submissions'
    | '/_authenticated/support'
    | '/_authenticated/wallet'
    | '/_authenticated/workspace'
    | '/api/chat'
    | '/certificates/$code'
    | '/sitemap/xml'
    | '/u/$id'
    | '/u/@$username'
    | '/verify/$id'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/enrichment-runs'
    | '/_authenticated/admin/missing-videos'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/cohorts/$id'
    | '/_authenticated/courses/$slug'
    | '/_authenticated/creator/comments'
    | '/_authenticated/creator/earnings'
    | '/_authenticated/creator/subscribers'
    | '/_authenticated/creators/$id'
    | '/_authenticated/playground/challenges'
    | '/_authenticated/playground/editor'
    | '/_authenticated/playground/interview'
    | '/_authenticated/playground/leaderboard'
    | '/_authenticated/playground/projects'
    | '/_authenticated/playground/react'
    | '/_authenticated/playground/web'
    | '/api/webhooks/cashfree'
    | '/api/webhooks/cashfree-subscription'
    | '/_authenticated/courses/'
    | '/api/public/hooks/run-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CoachesRoute: typeof CoachesRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CreatorsRoute: typeof CreatorsRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  CertificatesCodeRoute: typeof CertificatesCodeRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  UIdRoute: typeof UIdRoute
  UAtusernameRoute: typeof UAtusernameRoute
  VerifyIdRoute: typeof VerifyIdRoute
  ApiWebhooksCashfreeRoute: typeof ApiWebhooksCashfreeRoute
  ApiWebhooksCashfreeSubscriptionRoute: typeof ApiWebhooksCashfreeSubscriptionRoute
  ApiPublicHooksRunRemindersRoute: typeof ApiPublicHooksRunRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/@$username': {
      id: '/u/@$username'
      path: '/u/@$username'
      fullPath: '/u/@$username'
      preLoaderRoute: typeof UAtusernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$code': {
      id: '/certificates/$code'
      path: '/certificates/$code'
      fullPath: '/certificates/$code'
      preLoaderRoute: typeof CertificatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playground': {
      id: '/_authenticated/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creator': {
      id: '/_authenticated/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AuthenticatedCreatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community-feed': {
      id: '/_authenticated/community-feed'
      path: '/community-feed'
      fullPath: '/community-feed'
      preLoaderRoute: typeof AuthenticatedCommunityFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts': {
      id: '/_authenticated/cohorts'
      path: '/cohorts'
      fullPath: '/cohorts'
      preLoaderRoute: typeof AuthenticatedCohortsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coaching': {
      id: '/_authenticated/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof AuthenticatedCoachingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apply-creator': {
      id: '/_authenticated/apply-creator'
      path: '/apply-creator'
      fullPath: '/apply-creator'
      preLoaderRoute: typeof AuthenticatedApplyCreatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools': {
      id: '/_authenticated/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AuthenticatedAiToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/webhooks/cashfree-subscription': {
      id: '/api/webhooks/cashfree-subscription'
      path: '/api/webhooks/cashfree-subscription'
      fullPath: '/api/webhooks/cashfree-subscription'
      preLoaderRoute: typeof ApiWebhooksCashfreeSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/cashfree': {
      id: '/api/webhooks/cashfree'
      path: '/api/webhooks/cashfree'
      fullPath: '/api/webhooks/cashfree'
      preLoaderRoute: typeof ApiWebhooksCashfreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playground/web': {
      id: '/_authenticated/playground/web'
      path: '/web'
      fullPath: '/playground/web'
      preLoaderRoute: typeof AuthenticatedPlaygroundWebRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/react': {
      id: '/_authenticated/playground/react'
      path: '/react'
      fullPath: '/playground/react'
      preLoaderRoute: typeof AuthenticatedPlaygroundReactRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/projects': {
      id: '/_authenticated/playground/projects'
      path: '/projects'
      fullPath: '/playground/projects'
      preLoaderRoute: typeof AuthenticatedPlaygroundProjectsRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/leaderboard': {
      id: '/_authenticated/playground/leaderboard'
      path: '/leaderboard'
      fullPath: '/playground/leaderboard'
      preLoaderRoute: typeof AuthenticatedPlaygroundLeaderboardRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/interview': {
      id: '/_authenticated/playground/interview'
      path: '/interview'
      fullPath: '/playground/interview'
      preLoaderRoute: typeof AuthenticatedPlaygroundInterviewRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/editor': {
      id: '/_authenticated/playground/editor'
      path: '/editor'
      fullPath: '/playground/editor'
      preLoaderRoute: typeof AuthenticatedPlaygroundEditorRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/challenges': {
      id: '/_authenticated/playground/challenges'
      path: '/challenges'
      fullPath: '/playground/challenges'
      preLoaderRoute: typeof AuthenticatedPlaygroundChallengesRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/creators/$id': {
      id: '/_authenticated/creators/$id'
      path: '/creators/$id'
      fullPath: '/creators/$id'
      preLoaderRoute: typeof AuthenticatedCreatorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creator/subscribers': {
      id: '/_authenticated/creator/subscribers'
      path: '/subscribers'
      fullPath: '/creator/subscribers'
      preLoaderRoute: typeof AuthenticatedCreatorSubscribersRouteImport
      parentRoute: typeof AuthenticatedCreatorRoute
    }
    '/_authenticated/creator/earnings': {
      id: '/_authenticated/creator/earnings'
      path: '/earnings'
      fullPath: '/creator/earnings'
      preLoaderRoute: typeof AuthenticatedCreatorEarningsRouteImport
      parentRoute: typeof AuthenticatedCreatorRoute
    }
    '/_authenticated/creator/comments': {
      id: '/_authenticated/creator/comments'
      path: '/comments'
      fullPath: '/creator/comments'
      preLoaderRoute: typeof AuthenticatedCreatorCommentsRouteImport
      parentRoute: typeof AuthenticatedCreatorRoute
    }
    '/_authenticated/courses/$slug': {
      id: '/_authenticated/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AuthenticatedCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/$id': {
      id: '/_authenticated/cohorts/$id'
      path: '/$id'
      fullPath: '/cohorts/$id'
      preLoaderRoute: typeof AuthenticatedCohortsIdRouteImport
      parentRoute: typeof AuthenticatedCohortsRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/missing-videos': {
      id: '/_authenticated/admin/missing-videos'
      path: '/missing-videos'
      fullPath: '/admin/missing-videos'
      preLoaderRoute: typeof AuthenticatedAdminMissingVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enrichment-runs': {
      id: '/_authenticated/admin/enrichment-runs'
      path: '/enrichment-runs'
      fullPath: '/admin/enrichment-runs'
      preLoaderRoute: typeof AuthenticatedAdminEnrichmentRunsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/run-reminders': {
      id: '/api/public/hooks/run-reminders'
      path: '/api/public/hooks/run-reminders'
      fullPath: '/api/public/hooks/run-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminEnrichmentRunsRoute: typeof AuthenticatedAdminEnrichmentRunsRoute
  AuthenticatedAdminMissingVideosRoute: typeof AuthenticatedAdminMissingVideosRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminEnrichmentRunsRoute: AuthenticatedAdminEnrichmentRunsRoute,
  AuthenticatedAdminMissingVideosRoute: AuthenticatedAdminMissingVideosRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCohortsRouteChildren {
  AuthenticatedCohortsIdRoute: typeof AuthenticatedCohortsIdRoute
}

const AuthenticatedCohortsRouteChildren: AuthenticatedCohortsRouteChildren = {
  AuthenticatedCohortsIdRoute: AuthenticatedCohortsIdRoute,
}

const AuthenticatedCohortsRouteWithChildren =
  AuthenticatedCohortsRoute._addFileChildren(AuthenticatedCohortsRouteChildren)

interface AuthenticatedCreatorRouteChildren {
  AuthenticatedCreatorCommentsRoute: typeof AuthenticatedCreatorCommentsRoute
  AuthenticatedCreatorEarningsRoute: typeof AuthenticatedCreatorEarningsRoute
  AuthenticatedCreatorSubscribersRoute: typeof AuthenticatedCreatorSubscribersRoute
}

const AuthenticatedCreatorRouteChildren: AuthenticatedCreatorRouteChildren = {
  AuthenticatedCreatorCommentsRoute: AuthenticatedCreatorCommentsRoute,
  AuthenticatedCreatorEarningsRoute: AuthenticatedCreatorEarningsRoute,
  AuthenticatedCreatorSubscribersRoute: AuthenticatedCreatorSubscribersRoute,
}

const AuthenticatedCreatorRouteWithChildren =
  AuthenticatedCreatorRoute._addFileChildren(AuthenticatedCreatorRouteChildren)

interface AuthenticatedPlaygroundRouteChildren {
  AuthenticatedPlaygroundChallengesRoute: typeof AuthenticatedPlaygroundChallengesRoute
  AuthenticatedPlaygroundEditorRoute: typeof AuthenticatedPlaygroundEditorRoute
  AuthenticatedPlaygroundInterviewRoute: typeof AuthenticatedPlaygroundInterviewRoute
  AuthenticatedPlaygroundLeaderboardRoute: typeof AuthenticatedPlaygroundLeaderboardRoute
  AuthenticatedPlaygroundProjectsRoute: typeof AuthenticatedPlaygroundProjectsRoute
  AuthenticatedPlaygroundReactRoute: typeof AuthenticatedPlaygroundReactRoute
  AuthenticatedPlaygroundWebRoute: typeof AuthenticatedPlaygroundWebRoute
}

const AuthenticatedPlaygroundRouteChildren: AuthenticatedPlaygroundRouteChildren =
  {
    AuthenticatedPlaygroundChallengesRoute:
      AuthenticatedPlaygroundChallengesRoute,
    AuthenticatedPlaygroundEditorRoute: AuthenticatedPlaygroundEditorRoute,
    AuthenticatedPlaygroundInterviewRoute:
      AuthenticatedPlaygroundInterviewRoute,
    AuthenticatedPlaygroundLeaderboardRoute:
      AuthenticatedPlaygroundLeaderboardRoute,
    AuthenticatedPlaygroundProjectsRoute: AuthenticatedPlaygroundProjectsRoute,
    AuthenticatedPlaygroundReactRoute: AuthenticatedPlaygroundReactRoute,
    AuthenticatedPlaygroundWebRoute: AuthenticatedPlaygroundWebRoute,
  }

const AuthenticatedPlaygroundRouteWithChildren =
  AuthenticatedPlaygroundRoute._addFileChildren(
    AuthenticatedPlaygroundRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAiToolsRoute: typeof AuthenticatedAiToolsRoute
  AuthenticatedApplyCreatorRoute: typeof AuthenticatedApplyCreatorRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedCoachingRoute: typeof AuthenticatedCoachingRoute
  AuthenticatedCohortsRoute: typeof AuthenticatedCohortsRouteWithChildren
  AuthenticatedCommunityFeedRoute: typeof AuthenticatedCommunityFeedRoute
  AuthenticatedCreatorRoute: typeof AuthenticatedCreatorRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPlaygroundRoute: typeof AuthenticatedPlaygroundRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedCoursesSlugRoute: typeof AuthenticatedCoursesSlugRoute
  AuthenticatedCreatorsIdRoute: typeof AuthenticatedCreatorsIdRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAiToolsRoute: AuthenticatedAiToolsRoute,
  AuthenticatedApplyCreatorRoute: AuthenticatedApplyCreatorRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedCoachingRoute: AuthenticatedCoachingRoute,
  AuthenticatedCohortsRoute: AuthenticatedCohortsRouteWithChildren,
  AuthenticatedCommunityFeedRoute: AuthenticatedCommunityFeedRoute,
  AuthenticatedCreatorRoute: AuthenticatedCreatorRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPlaygroundRoute: AuthenticatedPlaygroundRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedCoursesSlugRoute: AuthenticatedCoursesSlugRoute,
  AuthenticatedCreatorsIdRoute: AuthenticatedCreatorsIdRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CoachesRoute: CoachesRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CreatorsRoute: CreatorsRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  ShowcaseRoute: ShowcaseRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  CertificatesCodeRoute: CertificatesCodeRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  UIdRoute: UIdRoute,
  UAtusernameRoute: UAtusernameRoute,
  VerifyIdRoute: VerifyIdRoute,
  ApiWebhooksCashfreeRoute: ApiWebhooksCashfreeRoute,
  ApiWebhooksCashfreeSubscriptionRoute: ApiWebhooksCashfreeSubscriptionRoute,
  ApiPublicHooksRunRemindersRoute: ApiPublicHooksRunRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
