// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest, getCookie } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL =
      process.env.SUPABASE_URL ||
      process.env.NEXT_PUBLIC_SUPABASE_URL ||
      process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_ANON_KEY ||
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL or VITE_SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY
          ? ["SUPABASE_PUBLISHABLE_KEY or SUPABASE_ANON_KEY or NEXT_PUBLIC_SUPABASE_ANON_KEY"]
          : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in your .env or deployment environment.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    let token = "";
    const authHeader = request.headers.get("authorization");

    if (authHeader && authHeader.startsWith("Bearer ")) {
      token = authHeader.replace("Bearer ", "");
    } else {
      // Try multiple possible cookie names that Supabase uses
      const cookieNames = [
        "sb-access-token",
        "sb-refresh-token",
        "supabase-auth-token",
        "sb-auth-token",
      ];
      
      // Also check for any cookie starting with "sb-"
      const cookieHeader = request.headers.get("cookie") || "";
      const cookies = cookieHeader.split(";").map(c => c.trim());
      
      for (const cookie of cookies) {
        const [name, value] = cookie.split("=");
        if (name.startsWith("sb-") && value) {
          token = value;
          break;
        }
        // Also check our predefined names
        if (cookieNames.includes(name) && value) {
          token = value;
          break;
        }
      }
      
      // Fallback to specific cookie getter
      if (!token) {
        for (const name of cookieNames) {
          const val = getCookie(name);
          if (val) {
            token = val;
            break;
          }
        }
      }
    }

    if (!token) {
      console.log(
        "[auth-middleware] No token found! Headers:",
        Object.fromEntries(request.headers.entries()),
      );
      throw new Error("Unauthorized: No authorization header provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      console.error("[auth-middleware] Token validation failed:", error?.message);
      throw new Error("Unauthorized: Invalid token");
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: data.user.app_metadata,
      },
    });
  },
);
